var countries = ["aangeboren",
"aanvang",
"abidov,_a.,_et_al._2005",
"abidov,_a.,_rozanski,_a.,_hachamovitch,_r.,_hayes,_s.w.,_aboul-enein,_f.,_cohen,_i.,_et_al._(2005)._prognostic_significance_of_dyspnea_in_patients_referred_for_cardiac_stress_testing._the_new_england_journal_of_medicine,_353,_1889-1898._[online]_http",
"accurso,_f.j.,_et_al._2010",
"accurso,_f.j.,_rowe,_s.m.,_clancy,_j.p.,_boyle,_m.p.,_dunitz,_j.m.,_durie,_p.r.,_et_al._(2010)._effect_of_vx-770_in_persons_with_cystic_fibrosis_and_the_g551d-cftr_mutation._the_new_england_journal_of_medicine,_363,_1991-2003._[online]_http",
"ademnood",
"alexander,_e.k.,_et_al._2012",
"alexander,_e.k.,_kennedy,_g.c.,_baloch,_z.w.,_cibas,_e.s.,_chudova,_d.,_james_diggans,_j.,_et_al._(2012)._preoperative_diagnosis_of_benign_thyroid_nodules_with_indeterminate_cytology._the_new_england_journal_of_medicine,_367,_705-15._[online]_http",
"algemeen_nederlands_woordenboek",
"algemeen_nederlands_woordenboek._(2014)._[online]_http",
"aneurism",
"aneurysm",
"aneurysma",
"anheim,_m.,_et_al._2012",
"anheim,_m.,_tranchant,_c._&_koenig,_m._(2012).the_autosomal_recessive_cerebellar_ataxias._the_new_england_journal_of_medicine,_366,_636-646._[online]_http",
"anoop,_t.m._&_george,_k.c._(2011)._differential_clubbing_and_cyanosis._the_new_england_journal_of_medicine,_364,_666._[online]_http",
"anoop,_t.m._&_george,_k.c._2011",
"apicaal",
"apical",
"appels,_c.w.y._&_kloppenburg,_m._(2006)._het_muckle-wells-syndroom",
"appels,_c.w.y._&_kloppenburg,_m._2006",
"arbuckle,_m.r.,_et_al._2003",
"arbuckle,_m.r.,_mcclain,_m.t.,_rubertone,_m.v.,_scofield,_r.h.,_dennis,_g.j.,_james,_j.a.,_et_al._(2003)._development_of_autoantibodies_before_the_clinical_onset_of_systemic_lupus_erythematosus._the_new_england_journal_of_medicine,_349,_1526-33._[online]_http",
"ataxia",
"ataxie",
"ataxy",
"atkinson,_s._&_fox,_s.b._(2004)._vascular_endothelial_growth_factor_(vegf)-a_and_platelet-derived_growth_factor_(pdgf)_play_a_central_role_in_the_pathogenesis_of_digital_clubbing._the_journal_of_pathology,_203(2),_721-728._[online]_http",
"atkinson,_s._&_fox,_s.b._2004",
"baatenburg_de_jong,_a.,_et_al._2006",
"baatenburg_de_jong,_a.,bekhof,_j.,_zwart,_p.,_langenhorst,_v.j._&_roorda,_r.j._(2006)._ontwikkelingsachterstand_bij_borstgevoede_kinderen_door_ontoereikend_dieet_van_de_moeder._nederlands_tijdschrift_voor_geneeskunde,_150,_465-9._[online]_http",
"barlo,_n.p.,_et_al._2009",
"barlo,_n.p.,_van_moorsel,_d.h.m.,_van_den_bosch,_j.m.m,_van_de_graaf,_e.a.,_kwakkel-van_erp,_j.m._&_grutters,_j.c._(2009)._idiopathische_pulmonale_fibrose;_beschrijving_van_een_nederlands_cohort._nederlands_tijdschrift_voor_geneeskunde,_153,_b425._[online]_http",
"bartalena,_l.,_et_al._1898",
"bartalena,_l.,_marcocci,_c.,_bogazzi,_f.,_manetti,_l.,_tanda,_m.l.,_dell’unto,_e.,_et_al._(1998)._relation_between_therapy_for_hyperthyroidism_and_the_course_of_graves’_ophthalmopathy._the_new_england_journal_of_medicine,_388(2),_73._[online]_http",
"beerendonk,_c._c._m.,_dunselman,_g._a._j.,_hilders,_c._g._j._m.,_&_tissing,_w._j._e._(2007)._hoofdstuk_4._stand_van_zaken_met_betrekking_tot_het_invriezen_en_het_terugplaatsen_van_ovariumweefsel_voor_het_behoud_van_vruchtbaarheid._in_richtlijn_cryopreservatie_van_ovariumweefsel_(pp._35-64)._utrecht",
"beerendonk,_c._c._m.,_et_al._2007",
"begin",
"berger,_r.m.f_&_bogers,_a.j.j.c._(1994)._onderkenning_van_cyanose_bij_de_pasgeborene",
"berger,_r.m.f_&_bogers,_a.j.j.c._1994",
"bernstein,_j.g._&_daams,_j._(1790)._nieuw_heelkundig_woordenboek,_bevattende_de_nieuwste_ontdekkingen,_die,_in_de_laatste_jaren,_in_de_heelkunde_gedaan_zijn,_vol_1._haarlem",
"bernstein,_j.g._&_daams,_j._1790",
"besselink,_m.g.h.,_bollen,_t.l.,_boermeester,_m.a.,_van_ramshort,_b.,_van_leeuwen,_m.s._&_gooszen,_h.g._(2005)._timing_en_keuze_van_interventie_bij_necrotiserende_pancreatitis._nederlands_tijdschrift_voor_geneeskunde,_149,_501-6._[online]_http",
"besselink,_m.g.h.,_et_al._2005",
"bindweefselgezwel",
"birks,_e.j.,_et_al._2013",
"birks,_e.j.,_tansley,_p.d.,_hardy,_j.,_george,_r.s.,_bowles,_c.t.,_burke,_m.,_et_al._(2013)._left_ventricular_assist_device_and_drug_therapy_for_the_reversal_of_heart_failure._the_new_england_journal_for_medicine,_355(18),_1876._[online]_http",
"bleeker,_f.e.,_et_al._2006",
"bleeker,_f.e.,_van_furth,_w.r.,_van_der_horst,_c.m.a.m.,_majoie,_c.b.l.m._&_koot,_r.w._(2006)._subtiele_huidafwijkingen_in_de_mediaanlijn_als_aanduiding_van_een_neurodermaal_sluitingsdefect._nederlands_tijdschrift_voor_geneeskunde,_150,_2061-6._[online]_http",
"bloem,_b.r.,_et_al._1998",
"bloem,_b.r.,_grimbergen,_y.a.m._&_roos,_r.a.c._(1998)._laat_de_parkinson-patiënt_niet_vallen!_nederlands_tijdschrift_voor_geneeskunde,_142,_2825-7._[online]_http",
"blokker,_r.s.,_et_al._2006",
"blokker,_r.s.,_smit,_l.m.e.,_van_den_bos,_c.,_overberg,_p.c.,_caron,_h.n._&_kaspers,_g.j.l._(2006)._een_jongen_met_acute_cerebellaire_ataxie_zonder_opsoclonus,_door_een_neuroblastoom._nederlands_tijdschrift_voor_geneeskunde,_150,_799-803._[online]_http",
"blossom,_d.b.,_et_al._2008",
"blossom,_d.b.,_kallen,_a.j.,_patel,_p.r.,_elward,_a.,_robinson,_l.,_gao,_g.,_et_al._(2008)._outbreak_of_adverse_reactions_associated_with_contaminated_heparin._the_new_england_journal_of_medicine,_359(25),_2682._[online]_http",
"boeckxstaens,_g.e.,_annese,_v.,_bruley_des_varannes,_s.,_chaussade,_s.,_costantini,_m.,_cuttitta,_a.,_et_al._(2011)._pneumatic_dilation_versus_laparoscopic_hellers_myotomy_for_idiopathic_achalasia._the_new_england_journal_of_medicine,_364,_1807-1816._[online]_http",
"boeckxstaens,_g.e.,_et_al._2011",
"boerlage-van_dijk,_k.,_et_al._2013",
"boerlage-van_dijk,_k.,_jansen,_r.,_van_den_brink,_r.b.a.,_van_herwerden,_l.a.,_kluin,_j.,_baan_jr.,_j.,_et_al._(2013)._mitralisklepinsufficiëntie",
"boll,_a.p.m._(2005)._28.1_incidentalomen._in_h.j._bonjer_(ed)._chirurgie_(pp.495_-502)._houten",
"boll,_a.p.m._2005",
"bonsel,_g.j._&_steegers,_e.a.p._(2011)._verschillen_in_perinatale_sterfte_tussen_provincies",
"bonsel,_g.j._&_steegers,_e.a.p._2011",
"boomsma,_l._j.,_de_boer,_m._j.,_bouma,_m.,_bär,_f._w._h._m.,_van_bentum,_s._t._b.,_lamfers,_e._j._p.,_et_al._(2005)._landelijke_transmurale_afspraak_beleid_na_een_doorgemaakt_myocardinfarct. huisarts_wet, 48(5),_3._[online]_https",
"boomsma,_l._j.,_et_al._2005",
"bos,_m.m.e.m.,_et_al._1993",
"bos,_m.m.e.m.,_weimann,_m.n.,_dur,_a.h.m._&_donker,_a.j.m._(1993)._het_aneurysma_van_de_a._lienalis;_vaak_miskend._nederlands_tijdschrift_voor_geneeskunde,_137,_1129-32._[online]_http",
"bredenoord,_a.j.,_et_al._2006",
"bredenoord,_a.j.,_weusten,_b.l.a.m.,_timmer,_r.,_vandevoorde,_r.r.a._&_smout,_a.j.p.m._(2006)._boeren_(ructus)._nederlands_tijdschrift_voor_geneeskunde,_150,_1385-9._[online]_http",
"breukels,_m.a.,_et_al._2003",
"breukels,_m.a.,_truyens,_n.d.m.,_brouwers,_h.a.a.,_van_der_ent,_c.k._&_arets,h.g.m._(2003)._vier_zuigelingen_met_congenitale_cysteuze_longafwijkingen",
"brewster,_j.a.,_et_al._2012",
"brewster,_j.a.,_garland,_e.m.,_biaggioni,_i.,_black,_b.k.,_ling,_j.f.,_shibao,_c.a.,_et_al._(2012)._diurnal_variability_in_orthostatic_tachycardia",
"bronzwaer,_s.l.a.m._&_de_groot,_c.j._(1997)._risicofactoren_voor_gecompliceerd_ziektebeloop_bij_kinderen_opgenomen_met_mazelen_in_een_filippijns_universitair_ziekenhuis._nederlands_tijdschrift_voor_geneeskunde,_141,_2492-5._[online]_http",
"bronzwaer,_s.l.a.m._&_de_groot,_c.j._1997",
"broos,_n.,_de_vries,_t.w._&_duiverman,_e.j._(2012)._inhalatieglucocorticoïden_en_gedragsveranderingen_bij_kinderen._nederlands_tijdschrift_voor_geneeskunde,_156,_a4778._[online]_http",
"broos,_n.,_et_al._2012",
"brus,_f.,_et_al._2006",
"brus,_f.,_vandewall,_m.,_molenschot,_m.m.c.,_van_setten,_p.a._&_landstra,_a.m._(2006)._beoordeling_van_hartgeruisen_bij_kinderen",
"brügemann,_j.,_et_al._2004",
"brügemann,_j.,_postema,_k.,_van_gelder,_i.c.,_oosterwijk,_m.h._&_van_veldhuisen,_d.j._(2004)._hartrevalidatie_bij_patiënten_met_een_aangeboren_hartafwijking,_een_implanteerbare_defibrillator_of_chronisch_hartfalen._nederlands_tijdschrift_voor_geneeskunde,_148,_1809-15._[online]_http",
"buist,_m.,_bernard,_s.,_nguyen,_t.v.,_moore,_g._&_anderson,_j._(2004)._association_between_clinically_abnormal_observations_and_subsequent_in-hospital_mortality",
"buist,_m.,_et_al._2004",
"bukman,_a.,_et_al._2000",
"bukman,_a.,_weinans,_m.j.n.,_nikkels,_p.g.j._&_van_loon,_a.j._(2000)._ernstige_malaria_tropica_in_de_zwangerschap",
"busger_op_vollenbroek,_r.j.g._&_de_weerd,_a.w._(2013)._stikgevoelens_in_de_nacht._nederlands_tijdschrift_voor_geneeskunde,_157,_a6204._[online]_http",
"busger_op_vollenbroek,_r.j.g._&_de_weerd,_a.w._2013",
"böhm,_f.j.,_et_al._1996",
"böhm,_f.j.,_hirasing,_r.a.,_vaandrager,_g.j.,_reeser,_h.m.,_bijlsma,_r._&_de_groot,_r.m._(1996)._afgenomen_vroege_sterfte_door_diabetes_mellitus_type_i_bij_0-19-jarigen_in_nederland._nederlands_tijdschrift_voor_geneeskunde,_140,_90-3._[online]_http",
"cabré,_m.t._(1999)._terminology",
"cabré,_m.t._1999",
"camara-lemarroy,_c.r._(2014)._remote_ischemic_preconditioning_as_treatment_for_non-ischemic_gastrointestinal_disorders",
"camara-lemarroy,_c.r._2014",
"camilleri,_m._(2012)._peripheral_mechanisms_in_irritable_bowel_syndrome._the_new_england_journal_of_medicine,_367,1626-1635._[online]_http",
"camilleri,_m._2012",
"castelein,_r.m._(2014)._het_nut_van_braces_bij_adolescente_idiopathische_scoliose._nederlands_tijdschrift_voor_geneeskunde,_158,_a7246._[online]_http",
"castelein,_r.m._2014",
"cbg-meb",
"chabas,_d.,_et_al._2010",
"chabas,_d.,_ness,_j.,_belman,_a.,_yeh,_e.a.,_kuntz,_n.,_gorman,_m.p.,_et_al._(2010)._younger_children_with_ms_have_a_distinct_csf_inflammatory_profile_at_disease_onset._neurology,_74(5),_399-405._[online]_http",
"chamuleau,_s.a.j.,_et_al._2005",
"chamuleau,_s.a.j.,_van_den_brink,_r.b.a.,_kloek,_j.j.,_broekhuis,_e.,_beaumont,_e.m.f.h._&_koster,_r.w._(2005)._complicaties_van_een_niet_herkend_hartinfarct._nederlands_tijdschrift_voor_geneeskunde,_149,_2593-9._[online]_http",
"chen,_p.,_et_al_2011",
"chen,_p.,_lin,_j.,_lu,_c.,_ong,_c.,_hsieh,_p.f.,_yang,_c.,_et_al._(2011)._carbamazepine-induced_toxic_effects_and_hla-b*1502_screening_in_taiwan._the_new_england_journal_of_medicine,_364,_1126-33._[online]_http",
"choi,_y.s.,_et_al._2011",
"choi,_y.s.,_kim,_b.,_joo,_j.,_park,_y.,_lee,_s.h._&_song,_b.y._(2011)._a_rare_case_of_epiphyseal_chondromyxoid_fibroma_of_the_proximal_tibia._korean_journal_of_radiology,_12(6),_761-764._[online]_http",
"clinical_key",
"clinical_key._(2012)._[online]_https",
"clubbing",
"clubbing",
"college_ter_beoordeling_van_geneesmiddelen_-_medicines_evaluation_board._(2008)._[online]_http",
"collins",
"collins._(2014)._[online]_http",
"congenitaal",
"congenital",
"cooke,_l.j.,_bowles,_k.m.,_craig,_j.i.o._&_sule,_o._(2006)._occupational_injury_in_a_fishmonger_with_a_macular_rash,_hepatosplenomegaly_and_pancytopenia._journal_of_clinical_pathology,_59(9),_993-994._[online]_http",
"cooke,_l.j.,_et_al._2006",
"cooper,_d.s._(2005)._antithyroid_drugs._the_new_england_journal_of_medicine,_352,_905-917._[online]_http",
"cooper,_d.s._2005",
"cornel,_m.c.,_de_walle,_h.e.k.,_haveman,_t.m,_spreen,_j.a.,_breed,_a.c._&_ten_kate,_l.p._(1991)._prevalenties_bij_de_geboorte_van_meer_dan_30_aangeboren_afwijkingen_in_noord-nederland._nederlands_tijdschrift_voor_geneeskunde,_135,_2032-6._[online]_http",
"cornel,_m.c.,_et_al._1991",
"couwenberg,_s.m,_et_al._1998",
"couwenberg,_s.m,_vuzevski,_v.d.,_heule,_f._&_siersema,_p.d._(1998)._nederlandse_vereniging_voor_dermatologie_en_venereologie._nederlands_tijdschrift_voor_geneeskunde,_142,_1579-84._[online]_http",
"curtis,_a.b.,_et_al._2013",
"curtis,_a.b.,_worley,_s.j.,_adamson,_p.b.,_chung,_e.s.,_niazi,_i.,_sherfesee,_l.,_et_al._(2013)._biventricular_pacing_for_atrioventricular_block_and_systolic_dysfunction._the_new_england_journal_of_medicine,_368,_1585-1593._[online]_http",
"cyanose",
"cyanosis",
"cypel,_m.,_et_al._2011",
"cypel,_m.,_yeung,_j.c.,_liu,_m.,_anraku,_m.,_chen,_f.,_karolak,_w.,_et_al._(2011)._normothermic_ex_vivo_lung_perfusion_in_clinical_lung_transplantation._the_new_england_journal_of_medicine,_364,_1431-40._[online]_http",
"da_silva-voorham,_j.m.,_et_al._2009",
"da_silva-voorham,_j.m.,_tami,_a.,_juliana,_a.e.,_rodenhuis-zybert,_i.a.,_wilschut,_j.c._&_smit,_j.m._(2009)._dengue",
"dalton,_e._(2011)._scoliosis",
"dalton,_e._2011",
"dankert-roelse,_j.e.,_et_al._2006",
"dankert-roelse,_j.e.,_mérelle,_m.e.,_laarman,_a.r.c._&_griffioen,_r.w._(2006)._jonge_kinderen_met_ernstige_afwijkingen_door_laat_herkende_cystische_fibrose._nederlands_tijdschrift_voor_geneeskunde,_150,_525-9._[online]_http",
"de_blok,_k.,_alberts,_chr.,_düren,_d.r._&_david,_g.k._(1991)._sarcoïdose_van_het_hart._nederlands_tijdschrift_voor_geneeskunde,_135,_475-8._[online]_http",
"de_blok,_k.,_et_al._1991",
"de_blok,_s._(1987)._focale_vulvitis._nederlands_tijdschrift_voor_geneeskunde,_131,_412._[online]_http",
"de_blok,_s._1987",
"de_boer,_k.,_büller,_h.r.,_ten_cate,_j.w.,_weenink,_g.h._&_treffers,_p.e._(1990)._diep_veneuze_trombose_in_de_zwangerschap",
"de_boer,_k.,_et_al._1990",
"de_bont,_e.g.p.m._&_cals,_j.w.l._(2014)._voor_elk_kind_met_koorts_een_eigen_‘stoplicht’?_nederlands_tijdschrift_voor_geneeskunde,_158,_a7649._[online]_http",
"de_bont,_e.g.p.m._&_cals,_j.w.l._2014",
"de_eerste_symptomen_van",
"de_geïntegreerde_taal-bank._(2010)._[online]_http",
"de_graaff,_j.c.,_et_al._2013",
"de_graaff,_j.c.,_van_der_werff,_d.b.m._&_kalkman,_c.j._(2013)._beschadigt_anesthesie_de_hersenontwikkeling_bij_kinderen?_nederlands_tijdschrift_voor_geneeskunde,_157,_a5198._[online]_http",
"de_haan,_s.n.,_et_al._2005",
"de_haan,_s.n.,_kinderman,_a.,_dahhan,_n._&_bosman,_d.k._(2005)._diagnostiek_naar_helicobacter_pylori-infectie_bij_kinderen._nederlands_tijdschrift_voor_geneeskunde,_149,_1326-9._http",
"de_jongh,_t.o.h._&_thiadens,_h.a._(2011)._onderzoek_van_de_longen_bij_verdenking_op_een_pneumonie._nederlands_tijdschrift_voor_geneeskunde,_155,_a2656._[online]_http",
"de_jongh,_t.o.h._&_thiadens,_h.a._2011",
"de_keyser,_r._(2006)._horen,_zien_en_tolken,_werken_als_tolk_in_de_sociale_sector._gent",
"de_keyser,_r._2006",
"de_kroon,_c.d.,_et_al._2003",
"de_kroon,_c.d.,_jansen,_f.w._&_trimbos,_j.b.m.z._(2003)._doelmatigheid_van_watercontrastechografie_ter_beoordeling_van_het_cavum_uteri._nederlands_tijdschrift_voor_geneeskunde,147,_1539-44._[online]_http",
"de_mol,_a.c.,_et_al.2006",
"de_mol,_a.c.,_vrancken,_s.,_eggink,_a.j.,_verduyn,_f.m._&_warris,_a._(2006)._de_eerste_pasgeborene_met_congenitaal_rubellasyndroom_tijdens_de_rubella-epidemie_in_nederland_in_2004/05._nederlands_tijdschrift_voor_geneeskunde,150,_741-6._[online]_http",
"de_vries,_m.,_et_al._1999",
"de_vries,_m.,_soetekouw,_p.m.m.b.,_van_bergen,_l.f.j.m.,_van_der_meer,_j.w.m._&_bleijenberg,_g._(1999)._lichamelijke_en_psychische_klachten_bij_militairen_na_oorlogshandelingen_en_vredesmissies._nederlands_tijdschrift_voor_geneeskunde,_143,_2557-62._[online]_http",
"de_vries,_t.w.,_duiverman,_e.j._&_rottier,_b.l._(2005)._wanneer_de_behandeling_van_kinderen_met_astma_faalt",
"de_vries,_t.w.,_et_al._2005",
"de_vries,_w.r._(1984)._ervaringen_in_de_chirurgische_behandeling_van_tumoren_en_tumorachtige_afwijkingen_van_de_borstrand._groningen",
"de_vries,_w.r._1984",
"defronzo,_r.a.,_et_al._2011",
"defronzo,_r.a.,_tripathy,_d.,_schwenke,_d.c.,_banerji,_m.,_bray,_g.a.,_buchanan.,_t.a.,_et_al._(2011)._pioglitazone_for_diabetes_prevention_in_impaired_glucose_tolerance._the_new_england_journal_of_medicine,_364(12),_1113._[online]_http",
"delsing,_c.e.,_ardesch,_j.,_nihom,_j.,_mulder,_l.,_kootstra,_g.j._&_hylkema,_b.s._(2005)._een_ongewone_oorzaak_van_meningo-encefalitis",
"delsing,_c.e.,_et_al._2005",
"derks,_t.g.j.,_et_al._2004",
"derks,_t.g.j.,_jakobs,_h.,_gerding,_a.,_niezen-koning,_k.e.,_reijngoud,_d-j._&_smit,_g.p.a._(2004)._deficiëntie_van_het_vetzuuroxidatie-enzym_middenketen-acyl-coënzym-a-dehydrogenase_(mcad)_bij_een_volwassene,_opgespoord_tijdens_een_proefproject_voor_neonatale_screening._nederlands_tijdschrift_voor_geneeskunde,_148,_2185-90._[online]_http",
"desmet,_w.j.r.,_adriaenssens,_b.f.m._&_dens,_j.a.y._(2003)._apical_ballooning_of_the_left_ventricle",
"desmet,_w.j.r.,_et_al._2003",
"diaforese",
"diaphoresis",
"diepstraten,_a.f.m.,_bos,_c.f.a._&_pruijs,_j.e.h._(1998)._honderd_jaar_orthopedie_in_nederland._viii._kinderorthopedie._nederlands_tijdschrift_voor_geneeskunde,_142,_1119-24._[online]_http",
"diepstraten,_a.f.m.,_et_al_1998",
"distensie",
"distension",
"distention",
"dokterdokter.nl",
"dokterdokter.nl._(s.d.)._[online]_http",
"drent,_d._&_bast,_d._(2003)._longfibrose",
"drent,_d._&_bast,_d._2003",
"dyspnea",
"dyspneu",
"dyspnoea",
"ebaugh,_j.l._&_raffetto,_j.d._(2010)._giant_abdominal_aortic_aneurysm._the_new_england_journal_of_medicine,_362(1),_66._[online]_http",
"ebaugh,_j.l._&_raffetto,_j.d._2010",
"edeling,_w.m.,_et_al._2004",
"edeling,_w.m.,_verweij,_j.j.,_ponsioen,_c.ij._&_visser,_l.g._(2004)._uitbraak_van_amoebiasis_in_een_nederlands_gezin;_tropen_onverwacht_dichtbij._nederlands_tijdschrift_voor_geneeskunde,_148,_1830-4._[online]_http",
"edema",
"eijkman,_c._(2008)._over_gezondheid_en_ziekte_in_heete_gewesten._(j._van_druten)._http",
"eijkman,_c._2008",
"eijsackers,_m.f.,_et_al._2010",
"eijsackers,_m.f.,_tijsterman,_j.,_van_de_linde,_p._van_rooden,_j.k._&_merkus,_j.w.s._desmoïdtumoren_in_de_buikwand._nederlands_tijdschrift_voor_geneeskunde,_155,_a1487._[online]_http",
"elridge,_l._&_about.com_guide._(2012)._clubbing._[online]_http",
"elridge,_l._&_about.com_guide_2012",
"erytheem",
"erythema",
"eversole,_l.r._(2011)._odontogenic_fibroma,_including_amyloid_and_ossifying_variants._head_and_neck_pathology,_5(4),_335-343._[online]_http",
"eversole,_l.r._2011",
"ewals,_j.a.p.m._(2005)._brucellose_als_importziekte_bij_een_jonge_man_met_arthritis._nederlands_tijdschrift_voor_geneeskunde,_149,_2810-4._[online]_http",
"ewals,_j.a.p.m._2005",
"failure_to_thrive",
"faller,_b.a._&_atkinson,_j.p._(2008)._new-onset_clubbing_associated_with_lung_cancer._the_new_england_journal_for_medicine,_359,_e15._[online]_http",
"faller,_b.a._&_atkinson,_j.p._2008",
"fibroma",
"fibroom",
"fiskerstrand,_t.,_arshad,_n.,_haukanes,_b.i.,_tronstad,_r.r.,_pham,_k.d.,_johansson,_s.,_et_al._(2012)._familial_diarrhea_syndrome_caused_by_an_activating_gucy2c_mutation._the_new_english_journal_of_medicine,_366,_1586-1595._[online]_http",
"fiskerstrand,_t.,_et_al._2012",
"fleuren,_m._a._h.,_kamphuis,_m.,_&_van_velzen-mol,_h._w._m._(2005)._determinantenanalyse_jgz-standaard_opsporing_van_aangeboren_hartafwijkingen._(tno_kwaliteit_van_leven)._[online]_http",
"fleuren,_m.a.h.,_et_al._2005",
"ford,_j.a.,_et_al._2013",
"ford,_j.a.,_lois,_n.,_royle,_p.,_clar,_c.,_shyangdan,_d._&_waugh,_n._(2013)._current_treatments_in_diabetic_macular_oedema",
"fowler,_j.,_jarratt,_m.,_moore,_a.,_meadows,_k.,_pollack,_a.,_steinhoff,_m.,_et_al._(2012)._once-daily_topical_brimonidine_tartrate_gel_0·5%_is_a_novel_treatment_for_moderate_to_severe_facial_erythema_of_rosacea",
"fowler,_j._et_al_2012",
"fried,_m.,_et_al._2000",
"fried,_m.,_mana,_f._&_urbain,_d._(2000)._cyanose_en_levercirrose",
"fushimi,_k.,_et_al._1993",
"fushimi,_k.,_uchida,_s.,_hara,_y.,_hirata,_y.,_marumo,_f._&_sasai,_s._(1993)._cloning_and_expression_of_apical_membrane_water_channel_of_rat_kidney_collecting_tubule._letters_to_nature,_361,_549._[online]_http",
"ganz,_r.a.,_et_al._2013",
"ganz,_r.a.,_peters,_j.h.,_horgan,_s.,_bemelman,_w.a.,_dunst,_c.m.,_edmundowicz, s.a.,_et_al._(2013)._esophageal_sphincter_device_for_gastroesophageal_reflux_disease._the_new_england_journal_of_medicine,_368,_719-727._[online]_http",
"gelderblom,_h._&_verweij,_j._(2003)._enkele_patiënten_met_een_gemetastaseerde_gastro-intestinale_stromaceltumor",
"gelderblom,_h._&_verweij,_j._2003",
"gerts,_m.j._&_de_jongh,_t.o.h._(1992)._kleine_kwalen_in_de_huisartsgeneeskunde;_keratitis_door_ultraviolette_straling._nederlands_tijdschrift_voor_geneeskunde,_136,_685-7._[online]_http",
"gerts,_m.j._&_de_jongh,_t.o.h._1992",
"geruis",
"gestippeld",
"gevlekt",
"gezondheidsplein.nl",
"gezondheidsplein.nl._[online]_http",
"ghorbanzadeh,_a.,_aminifar,_s.,_shadan,_l._&_ghanati,_h._(2013)._evaluation_of_three_methods_in_the_diagnosis_of_dentin_cracks_caused_by_apical_resection._journal_of_dentistry_(tehran),_10(2),_175–185._[online]_http",
"ghorbanzadeh,_a.,_et_al._2013",
"giard,_r.w.m._&_coebergh,_j.w.w._(1998)._de_keerzijde_van_diagnostische_ijver._nederlands_tijdschrift_voor_geneeskunde,_142,_2187-91._[online]_http",
"giard,_r.w.m._&_coebergh,_j.w.w._1998",
"ginghin?,_c.,_et_al._2012",
"ginghin?,_c.,_n?stase,_oa.,_ghiorghiu,_i._&_egher,_l._(2012)._continuous_murmur_-_the_auscultatory_expression_of_a_variety_of_pathological_conditions._journal_of_medicine_and_life,_5(1),_39-36._[online]_http",
"giugni,_a.s.,_et_al._2013",
"giugni,_a.s.,_mani,_s.,_kannan,_s.&_hatipoglu,_b._(2013)._exophthalmos",
"glosbe_en",
"glosbe_en._(s.d.)._[online]_http",
"govan,_d.e._&_fair,_w.r._(1974)._development_and_progression_of_clubbing_and_scarring_in_children_with_recurrent_urinary_tract_infections._radiology,_113,145-153._[online]_http",
"govan,_d.e._&_fair,_w.r._1974",
"grannas,_g.,_et_al._2014",
"grannas,_g.,_schrem,_h.,_klempnauer,_j._&_lehnera,_f._(2014)._ten_years_experience_with_belatacept-based_immunosuppression_after_kidney_transplantation._journal_of_clinical_medicine_research,_6(2),_98–110._[online]_http",
"gray,_a.,_et_al._2008",
"gray,_a.,_goodacre,_s.,_newby,_d.e.,_masson,_m.,_sampson,_f._&_nicholl,_j._(2008)._noninvasive_ventilation_in_acute_cardiogenic_pulmonary_edema._the_new_england_journal_of_medicine,_359,_142-151._[online]_http",
"groeiachterstand",
"guo,_w.,_et_al._2012",
"guo,_w.,_li,_q.,_boyce,_s.j.,_mcadams,_h.p.,_shiraishi,_j.,_doi,_k.,_et_al._(2012)._a_computerized_scheme_for_lung_nodule_detection_in_multiprojection_chest_radiography._medical_physics,_39(4),_2001-2012._[online]_http",
"hale,_s.b._(2007)._community_interpreting._hampshire",
"hale,_s.b._2007",
"hanck,_l._&_schellekens,_a.f.a._(2013)._persisterende_waarnemingsstoornissen_na_het_gebruik_van_ecstasy._nederlands_tijdschrift_voor_geneeskunde,_157,_a5649._[online]_http",
"hanck,_l._&_schellekens,_a.f.a._2013",
"hart,_w._(2002)._is_er_een_relatie_tussen_dyspepsie,_postprandiale_klachten_en_het_functioneren_van_de_maag?_nederlands_tijdschrift_voor_geneeskunde,_146,_777._[online]_http",
"hart,_w._(2005)._minder_symptomen_van_astma_bij_kinderen._nederlands_tijdschrift_voor_geneeskunde,_149,_2133._[online]_http",
"hart,_w._2002",
"hart,_w._2005",
"hartkloppingen",
"hartman,_t.c.,_et_al._2012",
"hartman,_t.c.,_van_ravesteijn,_h._&_lucassen,_p.l._(2012)._geluk_of_ongeluk_bij_een_hartstilstand._nederlands_tijdschrift_voor_geneeskunde,_156,_a5717._[online]_http",
"hazenberg,_a.,_hofker_s.s.,_van_der_aa,_j.g.,_nieuwenhuis,_j.a.,_kerstjens,_a.m._&_wijkstra,_p.j._(2013)._diafragmapacemaker",
"hazenberg_a.,_et_al._2013",
"healy,_z.r.,_dinkova-kostova,_a.t.,_wehage,_s.l.,_thompson,_r.e.,_fahey,_j.w._&_talalay,_p._(2009)._precise_determination_of_the_erythema_response_of_human_skin_to_ultraviolet_radiation_and_quantification_of_effects_of_protectors._photodermatol_photoimmunol_photomed,_25(1),_45–50._[online]_http",
"healy,_z.r.,_et_al._2009",
"heerdink-obenhuijsen,_n.,_et_al._2006",
"heerdink-obenhuijsen,_n.,_kamphuis,_m.,_fleuren,_m.a.h.,_van_velzen-mol,_h.w.m._&_de_wilde,_j.a._(2006)._de_standaard_vroegtijdige_opsporing_van_aangeboren_hartafwijkingen_0-19_jaar_van_de_jeugdgezondheidszorg._nederlands_tijdschrift_voor_geneeskunde,_150,_1764-7._[online]_http",
"hegedüs,_l._(2004)._the_thyroid_nodule._the_new_england_journal_of_medicine,_351,_1764-1771._[online]_http",
"hegedüs,_l._2004",
"heinerman,_b.c.c.,_et_al._2012",
"heinerman,_b.c.c.,_van_beynum,_i.m._&_buysse,_c.m.p._(2012)._syncope_op_de_kinderleeftijd",
"heisler,_j.r.n_&_about.com_guide._(2009)._congenital_definition_-_what_does_congenital_mean._[online]_http",
"heisler,_j.r.n_&_about.com_guide_2009",
"henebiens,_m.,_a.a.w._van_geloven,_a.a.w._&_gouma,_d.j._(2007)._diagnostiek_en_behandeling_bij_‘body-packer’-syndroom._nederlands_tijdschrift_voor_geneeskunde,_152,_1868-73._[online]_http",
"henebiens,_m.,_et_al._2007",
"hepatomegalie",
"hepatomegaly",
"hermans,_d.j.j.,_et_al._2011",
"hermans,_d.j.j.,_ottenhof,_m.,_wijnen,_m.h.w.a.,_van_beynum,_i.m.,_van_der_horst,_c.m.a.m._&_van_der_vleuten,_c.j.m._(2011)._behandeling_van_infantiele_hemangiomen_met_propranolol._nederlands_tijdschrift_voor_geneeskunde,_155,_a3482._[online]_http",
"heymans,_h.s.a.,_et_al._1990",
"heymans,_h.s.a.,_wanders,_r.j.a.,_schutgens,_r.b.h.,_van_den_bosch,_h.,_tager,_j.m._&_barth,_p.g._(1990)._zellweger-syndroom_en_andere_peroxisomale_ziekten",
"hiemstra,_p.s._&_stolk,_j._(2003)._van_gen_naar_ziekte;_[alpha]1-antitrypsinedeficiëntie._nederlands_tijdschrift_voor_geneeskunde,_147,_758-60._[online]_http",
"hiemstra,_p.s._&_stolk,_j._2003",
"hoeber,_m.,_et_al._2006",
"hoeber,_m.,_houben,_m.p.w.a.,_jansen,_b.p.w._&_de_kort_p.lm._(2006)._herseninfarct_na_cocaïnegebruik._nederlands_tijdschrift_voor_geneeskunde,_150,_2789-93._[online]_http",
"hoefnagel,_j.j.,_et_al._2010",
"hoefnagel,_j.j.,_wehmeijer,_k.,_terreehorst,_i._&_van_zuuren,_e._(2010)._angio-oedeem_en_urticaria_bij_frequent_gebruikte_geneesmiddelen._nederlands_tijdschrift_voor_geneeskunde,_154,_a1854._[online]_http",
"holland,_s.m.,_deleo,_f.r.,_elloumi,_h.z.,_hsu,_a.p.,_uzel,_g.,_brodsky,_n.,_et_al._(2007)._stat3_mutations_in_the_hyper-ige_syndrome._the_new_england_journal_of_medicine,_357,_1608-1619._[online]_http",
"holland,_s.m.,_et_al._2007",
"holleman,_f._(2014)._agressieve_behandeling_van_bloeddruk_en_lipiden_bij_diabetes_kan_dementie_niet_voorkomen._nederlands_tijdschrift_voor_geneeskunde,_158,_a7539._[online]_http",
"holleman,_f._2014",
"holman,_m.,_azizi,_n.,_ligtenberg,_j.j.m._&_ter_maaten,_j.c._(2014)._spoedechografie_bij_patiënten_met_shock._nederlands_tijdschrift_voor_geneeskunde,_158,_a6695._[online]_http",
"holman,_m.,_et_al._2014",
"holman,_m._&_ter_maaten,_j.c._(2010)._ernstige_metabole_acidose_door_5-oxoproline_bij_paracetamolgebruik._nederlands_tijdschrift_voor_geneeskunde,_154,_a1838._[online]_http",
"holman,_m._&_ter_maaten,_j.c._2010",
"honing,_m.l.h.,_bredie,_s.j.h._&_smulders,_y.m._(2005)._ziekte_van_de_aorta_bij_arteriitis_temporalis_en_polymyalgia_rheumatic._nederlands_tijdschrift_voor_geneeskunde,_149,_1947-53._[online]_http",
"honing,_m.l.h.,_et_al._2005",
"hordijk,_m.l._(1994)._echo-endoscopie_bij_de_diagnostiek_van_maligne_oesofagustumoren._nederlands_tijdschrift_voor_geneeskunde,_138,_2184-8._[online]_http",
"hordijk,_m.l._1994",
"horlogeglasnagels",
"houwerzijl,_e.j.,_et_al._2005",
"houwerzijl,_e.j.,_haelst,_p.l.,_doormaal,_j.j._&_gans,_r.o.b._(2005)._klinisch_denken_en_beslissen_in_de_praktijk._een_31-jarige_vrouw_met_voorbijgaande_visusklachten_en_polycytemie._nederlands_tijdschrift_voor_geneeskunde,_149,_125-31._[online]_http",
"hulscher,_j.b.f.,_et_al._2005",
"hulscher,_j.b.f.,_labohm,_j.,_goslings,_j.c.,_van_lienden,_k.p._&_aronson,_d.c._(2005)._kinderen_met_stomp_traumatisch_leverletsel._nederlands_tijdschrift_voor_geneeskunde,_149,_2705-11._[online]_http",
"hwang,_w.,_et_al._2012",
"hwang,_w.,_volk,_b.l.,_akberali,_f.,_singhal,_p.,_criscione,_j.c._&_maitland,_d.j._(2012)._estimation_of_aneurysm_wall_stresses_created_by_treatment_with_a_shape_memory_polymer_foam_device._biomech_model_mechanobiol,11(5),_715–729._[online]_http",
"idu,_s.r.,_et_al._1998",
"idu,_s.r.,_zimmerman,_c.,_mulder,_l._&_meis,_j.f.g.m._(1998)._een_zeer_ernstig_beloop_van_psittacose_in_de_zwangerschap._nederlands_tijdschrift_voor_geneeskunde,_142,_2586-9._[online]_http",
"ingels,_k.j.a.o._(2005)._3d-navigatie_in_de_neusbijholtechirurgie._nederlands_tijdschrift_voor_geneeskunde,_149,_1675-81._[online]_http",
"ingels,_k.j.a.o._2005",
"inl_gtb",
"interglot_en",
"interglot_en._(2014)._[online]_http",
"iturrino,_j.,_camilleri,_m.,_busciglio,_i.,_burton,_d._&_zinsmeister,_a.r._(2012)._sensations_of_gas_and_pain_and_their_relationship_to_compliance_during_distension_in_human_colon._neurogastroenterol_motil, 24(7),_646–e275._[online]_http",
"iturrino,_j.,_et_al._2012",
"jansen,_c.,_et_al._2005",
"jansen,_c.,_houben,_m.p.w.a.,_hoff,_j.i.,_sanchez-juan,_p.,_rozemuller,_a.j.m.,_&_van_duijn,_c.m._(2005)._de_eerste_patiënt_in_nederland_met_de_nieuwe_variant_van_de_ziekte_van_creutzfeldt-jakob._nederlands_tijdschrift_voor_geneeskunde,_149,_2949-54._[online]_http",
"jansen,_l._&_van_der_linden,_c.m.j._(2013)._vallen_door_een_vitamine_b12-deficiëntie._nederlands_tijdschrift_voor_geneeskunde,_157,_a5132._[online]_http",
"jansen,_l._&_van_der_linden,_c.m.j._2013",
"jansen,_m.,_et_al._2006",
"jansen,_m.,_van_dael,_c.m.l.,_verrijn_stuart,_a.a.,_van_der_hout,_a.h._&_rump,_p._(2006)._van_gen_naar_ziekte;_hypofosfatemische_rachitis_en_het_phex-gen._nederlands_tijdschrift_voor_geneeskunde,_150,_1390-4._[online]_http",
"jayaprakash,_k._&_karthikeyan,_a._(2008)._ocular_myasis_and_associated_mucopurulent_conjuctivitis_acquired_occupationally",
"jayaprakash,_k._&_karthikeyan,_a._2008",
"jennekens,_f.g.i._&_ippel,_p.f._(1993)._onderzoek_van_dna_en_dystrofine_bij_de_ziekten_van_duchenne_en_van_becker;_het_voordeel_voor_patiënten._nederlands_tijdschrift_voor_geneeskunde,_137,_61-3._[online]_http",
"jennekens,_f.g.i._&_ippel,_p.f._1993",
"jeong,_s.j._(2011)._nutritional_approach_to_failure_to_thrive._korean_journal_of_pediatrics,_54(7),_277-281._[online]_http",
"jeong,_s.j._2011",
"juffermans,_n.p.,_et_al._2006",
"juffermans,_n.p.,_rijneveld,_a.w.,_zweegeman,_s._&_spijkstra,_j.j._(2006)._twee_patiënten_met_lactaatacidose_en_hypoglykemie_als_uiting_van_een_lymfoom._nederlands_tijdschrift_voor_geneeskunde,_150,_2770-3._[online]_http",
"kawasaki,_s._&_kawasaki,_t._(2007)._evolution_of_a_thoracic_aortic_aneurysm._the_new_england_journal_of_medicine,_356,_1251._[online]_http",
"kawasaki,_s._&_kawasaki,_t._2007",
"kazmia,_i.,_et_al._2012",
"kazmia,_i.,_rahmanb,_m.,_afzala,_m.,_guptaa,_g.,_saleemc,_s.,_afzalc,_o.,_et_al._(2012)._anti-diabetic_potential_of_ursolic_acid_stearoyl_glucoside",
"kelleners-smeets,_n.w.j.,_bekkenk,_m.w._&_de_haas,_e.r.m._(2013)._huidkanker",
"kelleners-smeets,_n.w.j.,_et_al._2013",
"kersten,_v._(2013)._wat_u_moet_weten_over_het_scheuren_van_een_aneurysma._[online]_http",
"kersten,_v._2013",
"ki-won,_k.,_et_al._2010",
"ki-won,_k.,_hak_yong,_k.,_jin-kyong,_c.,_byung_ho,_c.,mee_kyung,_n.,_kwon,_w.,_et_al._(20120)._relationship_between_gallbladder_distension_and_lipid_profiles_in_kawasaki_disease._korean_circulation_journal,_40(3),_137–140._[online]_http",
"kievits,_f._&_adriaanse,_m.t._(2005)._gifstof_uit_printers._nederlands_tijdschrift_voor_geneeskunde,_149,_2369._[online]_http",
"kievits,_f._&_adriaanse,_m.t._2005",
"kievits,_f._(2001)._heilzaam_dodelijk_toxine._nederlands_tijdschrift_voor_geneeskunde,_145,_885._[online]_http",
"kievits,_f._2001",
"kingma,_m.l.,_et_al._2002",
"kingma,_m.l.,_van_krieken,_j.h.j.m.,_de_nef,_j.j.e.m._&_merth,_i.t._(2002)._aanhoudende_tachypneu_bij_een_zuigeling",
"klaveren,_r.j.,_oudkerk,_m.,_prokop,_m.,_scholten,_e.t.,_nackaerts,_k.,_vernhout,_r.,_et_al._(2009)._management_of_lung_nodules_detected_by_volume_ct_scanning._the_new_england_journal_of_medicine,_361,_2221-9._[online]_http",
"klein_nagelvoort,_r.w.,_et_al._2002",
"klein_nagelvoort,_r.w.,_hulstaert,_p.f.,_kon,_m._&_schuurman,_a.h._(2002)._necrotiserende_fasciitis_en_myositis_als_ernstige_complicaties_na_liposuctie._nederlands_tijdschrift_voor_geneeskunde,_146,_2430-5._[online]_http",
"klockgether,_t._&_paulson,_h._(2011)._movement_disorders_",
"klockgether,_t._&_paulson,_h._2011",
"knobbel",
"kodde,_j._&_allaart,_c._(2011)._afwijkingen_van_de_aorta_bij_patiënten_met_een_bicuspide_aortaklep._nederlands_tijdschrift_voor_geneeskunde,_155,_a4250._[online]_http",
"kodde,_j._&_allaart,_c._2011",
"kolader,_m.,_et_al._2004",
"kolader,_m.,_peerbooms,_p.g.h.,_van_voorst_vader,_p.c.,_van_bergen,_j.e.a.m.,_fennema,_j.s.a._&_de_vries,_h.j.c._(2004)._toename_van_fluorochinolonresistentie_bij_neisseria_gonorrhoeae_onder_bezoekers_van_de_soa-polikliniek_in_amsterdam;_cefotaxim_nu_als_eerste_keus_aanbevolen_voor_ongecompliceerde_gonorroe._nederlandse_tijdschrift_voor_geneeskunde,_148,_2129-32._[online]_http",
"konstan,_m.w.,_byard,_p.j.,_hoppel,_c.l._&_davis,_p.b._(1995)._effect_of_high-dose_ibuprofen_in_patients_with_cystic_fibrosis._the_new_england_of_medicine,_332(13),_848._[online]_http",
"konstan,_m.w.,_et_al._1995",
"koopmans,_n.g.,_et_al._2005",
"koopmans,_n.g.,_kwee,_w.s.,_grave,_w._&_stals,_f.s._(2005)._ernstige_diarree_met_invasieve_intestinale_spirochetose._nederlands_tijdschrift_voor_geneeskunde,_149,_2873-6._[online]_http",
"koopmans,_r.p.,_et_al._2003",
"koopmans,_r.p.,_van_den_born,_b.h.j.,_kersten,_m.j._&_hart,_w._(2003)._klinisch_denken_en_beslissen_in_de_praktijk._een_41-jarige_man_met_onbegrepen_periodieke_koorts._nederlands_tijdschrift_voor_geneeskunde,_147,_1778-83._[online]_http",
"kortademigheid",
"koster,_g.j.m.,_boersma,_w.g._&_de_graaff,_c.s._(2005)._verspringende_longinfiltraten_door_een_corpus_alienum._nederlands_tijdschrift_voor_geneeskunde,_149,_2868-72._[online]_http",
"koster,_g.j.m.,_et_al._2005",
"kovaleva,_j.,_et_al._2012",
"kovaleva,_j.,_gerhards,_l.g._&_möller,_a.v.m._(2012)._endocarditis_met_zeldzame_grampositieve_verwekkers._nederlands_tijdschrift_voor_geneeskunde,_156,_a4445._[online]_http",
"kroeze,_j._(2000)._de_biologische_basis_van_de_smaakwaarneming._neuropraxis,_4(5),_102-106._[online]_http",
"kroeze,_j._2000",
"kruijff,_s.,_et_al._2013_biblgegev>kruijff,_s.,_mastboom,_w.j.,_vriens,_m.r.,_sidhu,_s.b._&_delbridge,_l.w._(2013)._recidiverend_halsabces_door_een_kieuwboogfistel._nederlands_tijdschrift_voor_geneeskunde,_157,_a5806._[online]_http",
"kumar,_p._&_mckean,_m.c._(2004)._evidence_based_paediatrics",
"kumar,_p._&_mckean,_m.c._2004",
"kumar,_v._&_ogilvy,_c.s._(2011)._giant_intracranial_aneurysm._the_new_england_journal_of_medicine,_364(10),_956._[online]_http",
"kumar,_v_&_ogilvy,_c.s._2011",
"kumeliauskas,_l.,_et_al._2013",
"kumeliauskas,_l.,_fruetel,_k.,_&_holroyd-leduc,_j.m._(2013)._evaluation_of_older_adults_hospitalized_with_a_diagnosis_of_failure_to_thrive._canadian_geriatrics_journal,_16(2),_49-53._[online]_http",
"lambert,_j.,_&_bracke,_a._(2005)._cutane_manifestaties_van_endocrinologische_aandoeningen._nederlands_tijdschrift_voor_dermatologie_&_venereologie,_15,_394._[online]_http",
"lambert,_j._&_bracke,_a._2005",
"lamer,_f.p.l._&_bax,_j.j._(2006)._diagnose_in_beeld_(296)._een_vrouw_met_een_soufflé._nederlands_tijdschrift_voor_geneeskunde,_150,_2312._[online]_http",
"lamer,_f.p.l._&_bax,_j.j._2006",
"lamme,_b.,_et_al._2003",
"lamme,_b.,_spoestra,_f.o.b._&_lastdrager,_w.b._(2003)._diagnose_in_beeld_(144)._een_man_met_trommelstokvingers._nederlands_tijdschrift_voor_geneeskunde,_147,_1216._[online]_http",
"landolfi,_a.,_et_al._2013",
"landolfi,_a.,_giovannetti,_a.,_mancarella,_p.,_conti,_s.,_morgagni,_f._&_de_angelis,_c._(2013)._bilateral_chemodectoma",
"lees,_a.j.,_et_al._2012",
"lees,_a.j.,_woodward,_r.m.p.,_scott,_a.e.m._&_eadie,_m.j._(2012)._w_r_gowers_1895",
"lerner,_e.b.,_et_al._2000",
"lerner,_e.b.,_jehle,_d.v.k.,_janicke,_d.m._&_moscati,_r.m._(2000)._medical_communication",
"leververgroting",
"levi,_m.,_et_al._2000",
"levi,_m.,_schreuder,_m.j.c._&_hart,_w._(2000)._fysische_diagnostiek_-_percussie_en_palpatie_van_de_lever._nederlands_tijdschrift_voor_geneeskunde,_144,_835-8._[online]_http",
"ley,_p.,_et_al._1976",
"ley,_p.,_whitworth,_m.a.,_skilbeck,_c.e.,_woodward,_r.,_pinsent,_r.j.,_pike,_l.a.,_et_al._(1976)._improving_doctor-patient_communication_in_general_practice._the_journal_of_the_royal_college_of_the_general_practitioners,_26(171),_720–724._[online]_http",
"licht-strunk,_e._&_koch,_w._(2008)._de_standaard_kinderen_met_koorts_(tweede_herziening)_van_het_nederlands_huisartsen_genootschap;_reactie_vanuit_de_huisartsgeneeskunde._nederlands_tijdschrift_voor_geneeskunde,_152,_2763-5._[online]_http",
"licht-strunk,_e._&_koch,_w._2008",
"linguraru,_m.g.,_et_al_2012",
"linguraru,_m.g.,_sandberg,_j.k.,_jones,_e.c.,_petrick,_n.,_&_summers,_r.m._(2012)._assessing_hepatomegaly",
"list_and_glossary_of_medical_terms",
"löwenberg,_b.,_et_al._2009",
"löwenberg,_b.,_ossenkoppele,_g.j.,_van_putten,_w.,_schouten,_h.c.,_graux,_c._&_ferrant,_a.,_et_al._(2009)._high-dose_daunorubicin_in_older_patients_with_acute_myeloid_leukemia._the_new_england_journal_of_medicine,_361,_1235-48._[online]_http",
"macular",
"maillette_de_buy_wenniger,_l._2013-1",
"maillette_de_buy_wenniger,_l._2013-2",
"maillette_de_buy_wenninger,_l._(2013)._meta-analyse",
"maillette_de_buy_wenninger,_l._(2013)._studie_naar_risicofactoren_voor_ruptuur_intracranieel_aneurysma._nederlands_tijdschrift_voor_geneeskunde,_157,_c1705._[online]_http",
"mannes,_g.p.m._&_heijerman,_h.g.m._(1997)._cystische_fibrose",
"mannes,_g.p.m._&_heijerman,_h.g.m._1997",
"marcellin,_p.,_et_al._2008",
"marcellin,_p.,_heathcote,_e.j.,_buti,_m.,_gane,_e.,_de_man,_r.a.,_krastev,_z.,_et_al._(2008)._tenofovir_disoproxil_fumarate_versus_adefovir_dipivoxil_for_chronic_hepatitis_b._the_new_england_journal_of_medicine,_359,_2442-55._[online]_http",
"marcocci,_c.,_et_al._2011",
"marcocci,_c.,_kahaly,_g.j.,_krassas,_g.e.,_bartalena,_l.,_prummel,_m.,_stahl,_m.,_et_al._(2011)._selenium_and_the_course_of_mild_graves’_orbitopathy._the_new_england_journal_of_medicine,_364,_1920­31._[online]_http",
"marijon,_e.,_et_al._2007",
"marijon,_e.,_ou,_p.,_celermajer,_d.s.,_ferreira,_b.,_mocumbi,_a.o.,_jani,_d.,_et_al._(2007)._prevalence_of_rheumatic_heart_disease_detected_by_echocardiographic_screening._the_new_england_journal_of_medicine,_357,_470­6._[online]_http",
"marinkovic,_m.,_et_al._2002",
"marinkovic,_m.,_van_lanschot,_j.j.b.,_schlingemann,_r.o.,_de_smet,_m.d._&_saeed,_p._(2002)._oogklachten_wijzend_op_een_tumor_elders_in_het_lichaam._nederlands_tijdschrift_voor_geneeskunde,_146,_2393-6._[online]_http",
"maynard,_m.a.,_et_al._2014",
"maynard,_m.a.,_marino-enriquez,_a.,_fletcher,_j.a.,_dorfman,_d.m.,_raut,_c.p.,_yassa,_l.,_et_al._(2014)._thyroid_hormone_inactivation_in_gastrointestinal_stromal_tumors._the_new_england_journal_of_medicine,_370,_1327-1334._[online]_http",
"mdh_e8",
"medisch-woordenboek.nl",
"medisch-woordenboek.nl._(2012)._[online]_http",
"medterms_dictionary",
"medterms_dictionary._(2012)._[online]_http",
"meesters,_p.d.,_comijs,_h.c.,_de_haan,_l.,_smit,_j.h.,_eikelenboom,_p.,_beekman,_a.t.f.,_et_al._(2012)._minderheid_van_oudere_patiënten_met_schizofrenie_in_symptomatische_remissie._nederlands_tijdschrift_voor_geneeskunde,_156,_a4701._[online]_http",
"meesters,_p.d.,_et_al._2012",
"mekkes,_j.r._(2002)._tazaroteencrème_vermindert_rimpels_in_zon-beschadigde_huid._nederlands_tijdschrift_voor_geneeskdunde,_146,_642._[online]_http",
"mekkes,_j.r._2002",
"mentz,_r.j.,_et_al._2013",
"mentz,_r.j.,_hernandez,_a.f., stebbins,_a., ezekowitz,_j.a.,_felker,_g.m.,_heizer,_g.m.,_et_al._(2013)._predictors_of_early_dyspnoea_relief_in_acute_heart_failure_and_the_association_with_30-day_outcomes",
"merck_manual",
"merck_manual._(2013)._[online]_http",
"merideth,_m.a.,_et_al._2008",
"merideth,_m.a.,_gordon,l.b.,_clauss,_s.,_sachdev,_v.,_smith,_a.c.m.,_perry,_m.b.,_et_al._(2008)._phenotype_and_course_of_hutchinson–gilford_progeria_syndrome._the_new_england_journal_of_medicine,_358(6),_599._[online]_http",
"merkx,_m.a.w._&_bruaset,_i._(1995)._een_preauriculaire_zwelling",
"merkx,_m.a.w._&_bruaset,_i._1995",
"merriam-webster",
"merriam-webster._(2014)._[online]_http",
"mesh_browser",
"mesh_browser._(2014)._[online]_http",
"metra,_m.,_et_al._2010",
"metra,_m.,_teerlink,_j.r., felker,_g.m.,_greenberg,_b.h.,_filippatos,_g.,_ponikowski,_p.,_et_al._(2010)._dyspnoea_and_worsening_heart_failure_in_patients_with_acute_heart_failure",
"mevius,_l._(2011)._boksen",
"mevius,_l._(2012)._vallen_door_ssri’s_in_verpleeghuis._nederlands_tijdschrift_voor_geneeskunde,_156,_c1229._[online]_http",
"mevius,_l._(2012)._veel_overlevenden_non-hodgkinlymfoom_zijn_vermoeid._nederlands_tijdschrift_voor_geneeskunde,_156,_c1479._[online]_http",
"mevius,_l._(2014)._40_jaar_na_mustard-hartoperatie",
"mevius,_l._2011",
"mevius,_l._2012-1",
"mevius,_l._2012-2",
"mevius,_l._2014",
"michiels,_i._&_roumen,_f.j.m.e._(2004)._diagnose_in_beeld_(213)._een_zwangere_met_premature_contracties_en_vaginaal_bloedverlies._nederlands_tijdschrift_voor_geneeskunde,_148,_2174._[online]_http",
"michiels,_i._&_roumen,_f.j.m.e._2004",
"mijnwoordenboek_en",
"mijnwoordenboek_en._(2014)._[online]_http",
"mohangoo,_a.d._&_buitendijk,_s.e._(2009)._aangeboren_afwijkingen_in_nederland_1997-2007. gebaseerd_op_de_landelijke_verloskunde_en_neonatologie_registraties_leiden._(tno_kwaliteit_van_leven)._[online]_http",
"mohangoo,_a.d._&_buitendijk,_s.e._2009",
"mol,_p.g.m.,_et_al._2013",
"mol,_p.g.m.,_van_den_bemt,_p.m.l.a.,_dequito,_a.b.,_van_doormaal,_j.e.,_zaal,_r.j.,_haaijer-ruskamp,_f.m.,_et_al._(2013)._vermijdbare_en_niet-vermijdbare_medicatiegerelateerde_schade_in_het_ziekenhuis._nederlands_tijdschrift_voor_geneeskunde,157,_a5051._[online]_http",
"molkenboer,_j.f.m._&_hermans,_r.h.m._(2005)._een_vrouw_met_een_vulvaire_zwelling,_een_zeldzame_uiting_van_het_klippel-trenaunay-weber-syndroom._nederlands_tijdschrift_voor_geneeskunde,_149,_2287-9._[online]_http",
"molkenboer,_j.f.m._&_hermans,_r.h.m._2005",
"moll,_h.a._&_van_der_heijden,_a.j._(2008)._de_standaard_kinderen_met_koorts_(tweede_herziening)_van_het_nederlands_huisartsen_genootschap;_reactie_vanuit_de_kindergeneeskunde._nederlands_tijdschrift_voor_geneeskunde,_152,_2766-7._[online]_http",
"moll,_h.a._&_van_der_heijden,_a.j._2008",
"moll_van_charante,_e.p._&_de_jongh,_t.o.h._(2011)._onderzoek_bij_patiënten_met_een_acute_buik._nederlands_tijdschrift_voor_geneeskunde,_155,_a2658._[online]_http",
"moll_van_charante,_e.p._&_de_jongh,_t.o.h._2011",
"mosby._(2013)._mosby’s_medical_dictionary._st._louis,_missouri",
"mosby’s_medical_dictionary_2013",
"moss,_a.j.,_et_al._2012",
"moss,_a.j.,_schuger,_c.,_beck,_c.a.,_brown,_m.w.,_cannom,_d.s.,_daubert,_j.p.,_et_al._(2012)._reduction_in_inappropriate_therapy_and_mortality_through_icd_programming._the_new_england_journal_of_medicine,_367,_2275-2283._[online]_http",
"moussian,_b.,_et_al._2007",
"moussian,_b.,_veerkamp,_j.,_müller,_u._&_schwarz,_h._(2007)._assembly_of_the_drosophila_larval_exoskeleton_requires_controlled_secretion_and_shaping_of_the_apical_plasma_membrane._matrix_biology,_26(5),_337-347._[online]_http",
"mucopurulent",
"mucopurulent",
"mueller,_c.,_et_al._2004",
"mueller,_c.,_scholer,_a.,_laule-kilian,_k.,_martina,_b.,_schindler,_c.,_buser,_p.,_et_al._(2004)._use_of_b-type_natriuretic_peptide_in_the_evaluation_and_management_of_acute_dyspnea._the_new_england_journal_of_medicine,_350,_647-654._[online]_http",
"murmur",
"nadelman,_r.b.,_et_al._2012",
"nadelman,_r.b.,_hanincová,_k.,_mukherjee,_p.,_liveris,_d.,_nowakowski,_j.,_mckenna,_d.,_et_al._(2012)._differentiation_of_reinfection_from_relapse_in_recurrent_lyme_disease._the_new_england_journal_of_medicine,_367,_1883-90._[online]_http",
"nederlands-woordenboek",
"nederlands-woordenboek._(s.d.)._[online]_http",
"nederlands_tijdschrift_voor_geneeskunde._(s.d.)._[online]_http",
"nishiwaki,_s.,_araki,_h.,_hayashi,_m.,_takada,_j._iwashita,_m.,_tagami,_a.,_et_al._(2012)._inhibitory_effects_of_carbon_dioxide_insufflation_on_pneumoperitoneum_and_bowel_distension_after_percutaneous_endoscopic_gastrostomy._world_journal_of_gastroenterol",
"nishiwaki,_s.,_et_al._2012",
"nodule",
"noordam,_c.,_dhir,_v.,_mcnelis,_j.c.,_schlereth,_f.,_hanley,_n.a.,_krone,_n.,_et_al._(2009)._inactivating_papss2_mutations_in_a_patient_with_premature_pubarche._the_new_england_journal_of_medicine,_360,_2310-2318._[online]_http",
"noordam,_c.,_et_al._2009",
"noordegraaf,_a.,_boonstra,_a.b._&_postmus,_p.e._(2004)._handlezen_als_diagnosticum._nederlands_tijdschrift_voor_geneeskunde,_148,_53-6._[online]_http",
"noordegraaf,_a.,_et_al._2004",
"ntvg",
"nusmeier,_a.,_de_jongste,_j.c.,_bos,_a.p.,_lam,_j._&_hoekstra,_m.o._(2003)._klinisch_denken_en_beslissen_in_de_praktijk._een_pasgeborene_met_dyspnoe._nederlands_tijdschrift_voor_geneeskunde,_147,_1501-6._[online]_http",
"nusmeier,_a.,_et_al._2003",
"nützenadel,_w._(2011)._failure_to_thrive_in_childhood._deutsches_ärzteblatt_international,_108(38),_643-649._[online]_http",
"nützenadel,_w._2011",
"oedeem",
"oedema",
"olde_hartman,_t.c.,_et_al._2012",
"olde_hartman,_t.c.,_van_ravesteijn,_h._&_lucassen,_p.l._(2012)._geluk_of_ongeluk_bij_een_hartstilstand._nederlands_tijdschrift_voor_geneeskunde,_156,_a5717._[online]_http",
"online_etymology_dictionary",
"online_etymology_dictionary._(2014)._[online]_http",
"onset",
"opstelten,_w.,_eekhof,_j.a.h._&_neven,_a.k._(2011)._kinderziekten_met_vlekjes._nederlands_tijdschrift_voor_geneeskunde,_155,_a3671._[online]_http",
"opstelten,_w.,_et_al._2011",
"oxford_english_dictionary",
"oxford_english_dictionary._(2014)._[online]_http",
"palafox,_m.,_et_al._2000",
"palafox,_m.,_guiscafre,_h.,_reyes,_h.,_munoz,_o._&_martinez,_h._(2000)._diagnostic_value_of_tachypnoea_in_pneumonia_defined_radiologically._archives_of_disease_in_childhood,_82(1),_41–45._[online]_http",
"pang,_p.s.,_et_al._2009",
"pang,_p.s.,_konstam,_m.a.,_krasa,_h.b.,_swedberg,_k.,_zannad,_f.,_blair,_j.e.a.,_et_al._(2009)._effects_of_tolvaptan_on_dyspnoea_relief_from_the_everest_trials._eurean_heart_journal,_30(18),_2233–2240._[online]_http",
"pearson,_j._(1998)._terms_in_context._amsterdam",
"pearson,_j._1998",
"perloff,_j.k._(2012)._cyanotic_congenital_heart_disease_the_coronary_arterial_circulation._current_cardiology_reviews,_8(1),_1-5._[online]_http",
"perloff,_j.k._2012",
"pinkhof_geneeskundig_woordenboek",
"pinkhof_geneeskundig_woordenboek._(2012)._[online]_http",
"piérard,_l.a._&_lancellotti,_p._(2004)._the_role_of_ischemic_mitral_regurgitation_in_the_pathogenesis_of_acute_pulmonary_edema._the_new_england_journal_of_medicine,_351,_1627-1634._[online]_http",
"piérard,_l.a._&_lancellotti,_p._2004",
"piérard,_l.a._&_patrizio_lancellotti,_m.d._(2004)._the_role_of_ischemic_mitral_regurgitation_in_the_pathogenesis_of_acute_pulmonary_edema._the_new_england_journal_of_medicine,_351(16),_1628._[online]_http",
"pmc",
"pol,_f.j.m.,_et_al._2014",
"pol,_f.j.m.,_flucke,_u._&_jafari,_k._(2014)._intrathoracaal_hibernoom._nederlands_tijdschrift_voor_geneeskunde,_158,_a6610._[online]_http",
"poutanen,_s.m.,_et_al._2003",
"poutanen,_s.m.,_low,_d.e.,_henry,_b.,_finkelstein,_s.,_rose,_d.,_green,_k.,_et_al._(2003)._identification_of_severe_acute_respiratory_syndrome_in_canada._the_new_england_journal_of_medicine,_348,_1995-2005._[online]_http",
"powell,_f.c._(2005)._rosacea._the_new_england_journal_of_medicine,_352,_793-803._[online]_http",
"powell,_f.c._2005",
"prakken,_f.j.,_et_al._2011",
"prakken,_f.j.,_lelievel-vroom,_g.m.m.,_milinovic,_g.,_jacobi,_c.e.,_visser,_m.j.t._&_steenvoorde,_p._(2011)._meetbaar_verband_tussen_preventieve_interventies_en_de_incidentie_van_postoperatieve_wondinfecties._nederlands_tijdschrift_voor_geneeskunde,_155,_a3269._[online]_http",
"praveen,_r.s.,_pallavi,_v.r.,_rajashekar,_k.,_usha,_a.,_umadevi,_k._&_bafna,_u.d._(2013)._a_clinical_update_on_massive_ovarian_oedema_–_a_pseudotumour?_ecancermedicalscience,_7,_318._[online]_http",
"praveen,_r.s._et_al._2013",
"proptosis",
"proptosis",
"pruijm,_m.t.c.,_et_al._2003",
"pruijm,_m.t.c.,_falke,_t.h.m._&_peltenburg,_h.g._(2003)._retroperitoneale_bloeding_uit_een_renaal_angiomyolipoma._nederlands_tijdschrift_voor_geneeskunde,_147,_1696-9._[online]_http",
"pubmed_central._(2009)._[online]_http",
"reesink,_k.d.,_ferreira,_i.,_de_mey,_j.g.r._&_kuijpers,_n.h.l._(2011)._effect_of_transient_high_blood_glucose_level_on_brachial_artery_flow-mediated_dilation",
"reesink,_k.d_et_al._2011",
"reith,_n._(2005)._het_gaat_over!",
"reith,_n._2005",
"remenyi,_b._&_gentles,_t.l._(2012)._congenital_mitral_valve_lesions_",
"remenyi,_b._&_gentles,_t.l._2012",
"ringer._(1917)._de_invloed_van_adrenaline_op_zweet-afscheiding._nederlands_tijdschrift_voor_geneeskunde,_61,_30-1._[online]_http",
"ringer_1917",
"ripa,_r.s.,_et_al._2014",
"ripa,_r.s.,_kjaer,_a._&_hesse,_b._(2014)._non-invasive_imaging_for_subclinical_coronary_atherosclerosis_in_patients_with_peripheral_artery_disease._current_atherosclerosis_reports,_16,_415._[online]_http",
"rondeel,_j.m.m._(2007)._maligne_neurolepticasyndroom",
"rondeel,_j.m.m._2007",
"roos-hesselink,_j.w.,_et_al._1999",
"roos-hesselink,_j.w.,_meijboom,_f.j._&_spitaels,_s.e.c._(1999)._het_eisenmenger-syndroom_op_volwassen_leeftijd._nederlands_tijdschrift_voor_geneeskunde,_143,_501-5._[online]_http",
"ross,_d.s._(2011)._radioiodine_therapy_for_hyperthyroidism._the_new_england_journal_of_medicine,_364,_542-550._[online]_http",
"ross,_d.s._2011",
"rumping,_l.,_et_al._2014",
"rumping,_l.,_waterham,_h.r.,_kok,_i.,_van_hasselt,_p.m._&_visser,_g._(2014)._hereditaire_fructose-intolerantie._nederlands_tijdschrift_voor_geneeskunde,_158,_a6889._[onlline]_http",
"sager,_j.c._(1990)._a_practical_course_in_terminology_processing._amsterdam",
"sager,_j.c._1990",
"sagristà-sauleda,_j.,_angel,_j.,_sánchez,_a.,_permanyer-miralda,_g._&_soler-soler,_j._(2004)._effusive–constrictive_pericarditis._the_new_england_journal_of_medicine,_350,_469-475._[online]_http",
"sagristà-sauleda,_j.,_et_al._2004",
"samson,_r.a.,_et_al._2006",
"samson,_r.a.,_nadkarni,_v.m.,_meaney,_p.a.,_carey,_s.m.,_berg,_m.d._&_berg,_r.a._(2006)._outcomes_of_in-hospital_ventricular_fibrillation_in_children._the_new_england_journal_of_medicine,_354,_2328-2339._[online]_http",
"saraf,_a.,_et_al._2012",
"saraf,_a.,_franklin,_w.j.,_snyder,_c.s.,_fraser,_c.d._&_salazar,_j.d._(2012)._intermittent_cyanosis_years_after_a_mustard_repair_for_dextro-transposition_of_the_great_arteries._texas_heart_institute_journal,_39(5),_665–667._[online]_http",
"scheppink,_h.m.,_et_al._2012",
"scheppink,_h.m.,_ter_haar,_s.j.,_douw,_k.h.p.,_kamphuis,_m._&_boere-boonekamp,_m.m._(2012)._gebruik_van_de_‘jgz-richtlijn_vroegtijdige_opsporing_van_aangeboren_hartafwijkingen_0-19_jaar’._jgz_tijdschrift_voor_jeugdgezondheidszorg,_44(2),_26._[online]_http",
"scherpbier,_h.j._(1988)._aids_bij_kinderen._nederlands_tijdschrift_voor_geneeskunde,_132,_9-12._[online]_http",
"scherpbier,_h.j._1988",
"schildklier",
"scholten,_j.g.f._&_evert_j._buijs_(2014)._acute_pancreatitis_na_het_toedienen_van_propofol._nederlands_tijdschrift_voor_geneeskunde,_158,_a7115._[online]_http",
"scholten,_j.g.f._&_evert_j._buijs_2014",
"schuurman,_m.j.,_et_al._2014",
"schuurman,_m.j.,_loza,_b.,_de_vrie,_j._&_slabber,_a.j._(2014)._een_jong_kind_met_pulmonale_tuberculose._nederlands_tijdschrift_voor_geneeskunde,_158,_a6618._[online]_http",
"scoliose",
"scoliosis",
"service,_g.j.,_et_al._2005",
"service,_g.j.,_thompson,_g.b.,_service,_j.,_andrews,_j.c.,_collazo-clavell,_m.l._&_lloyd,_r.v._(2005)._hyperinsulinemic_hypoglycemia_with_nesidioblastosis_after_gastric-bypass_surgery.the_new_england_journal_of_medicine,_353(3),_249._[online]_http",
"shattuck,_t.m.,_et_al._2003",
"shattuck,_t.m.,_et_al._2005",
"shattuck,_t.m.,_välimäki,_s.,_obara,_t.,_gaz,_r.d.,_clark,_o.h.,_shoback,_d.,_et_al._(2003)._somatic_and_germ-line_mutations_of_the_hrpt2_gene_in_sporadic_parathyroid_carcinoma._the_new_england_journal_of_medicine,_349,_1722-9._[online]_http",
"shattuck,_t.m.,_westra,_w.h.,_ladenson,_p.w._&_arnold,_a._(2005)._independent_clonal_origins_of_distinct_tumor_foci_in_multifocal_papillary_thyroid_carcinoma._the_new_england_journal_of_medicine,_352,_2406-2412._[online]_http",
"shinde,_v.,_bridges,_c.b.,_uyeki,_t.m.,_shu,_b._&_balish,_a._(2009)._triple-reassortant_swine_influenza_a_(h1)_in_humans_in_the_united_states,_2005–2009._the_new_england_journal_of_medicine,_360,_2616-2625._[online]_http",
"shinde,_v.,_et_al._2009",
"sijbom,_m.,_et_al._2013",
"sijbom,_m.,_van_lieshout,_j.,_felix-schollaart,_b.,_burgers,_j.s._&_bouma,_m._(2013)._samenvatting_van_de_nhg-standaard_‘schildklieraandoeningen’._nederlands_tijdschrift_voor_geneeskunde,_157,_a6667._[online]_http",
"simonis,_r.f.a.,_et_al._1988",
"simonis,_r.f.a.,_janssens,_a.r.,_kroon,_h.m.,_terpstra,_j.l.,_van_krieken,_j.h.j.m.,_&_lamers,_c.b.h.w._(1988)._de_ziekte_van_caroli_beperkt_tot_één_leverkwab._nederlands_tijdschrift_voor_geneeskunde,_132,_80-3._[online]_http",
"skinner,_m.a.,_et_al._2005",
"skinner,_m.a.,_moley,_j.a.,_dilley,_w.g.,_owzar,_k.,_debenedetti,_m.k._&_wells,_s.a._(2005)._prophylactic_thyroidectomy_in_multiple_endocrine_neoplasia_type_2a._the_new_england_journal_of_medicine,_353,_1105-1113._[online]_http",
"skjerven,_h.o.,_et_al._2013",
"skjerven,_h.o.,_hunderi,_j.o.g.,_brügmann-pieper,_s.k.,_brun,_a.c.,_engen,_h.,_eskedal,_l.,_et_al._(2013)._racemic_adrenaline_and_inhalation_strategies_in_acute_bronchiolitis._the_new_england_journal_of_medicine,_368,_2286-2293._[online]_http",
"slee,_p.h.th.j._(2008)._casuistische_inwendige_geneeskunde",
"slee,_p.h.th.j._2008",
"sluiter,_h.e._(2013)._verschillen_in_richtlijnen_chronische_nierschade._nederlands_tijdschrift_voor_geneeskunde,_157,_a5679._[online]_http",
"sluiter,_h.e._2013",
"sluzewski,_h._(1988)._appendicitis_acuta._nederlands_tijdschrift_voor_geneeskunde,_132,_995-7._[online]_http",
"sluzewski,_h._1988",
"smit,_m.,_et_al._2014",
"smit,_m.,_kerstens,_m.n.,_boomsma-van_holten,_m.j.,_van_der_meer,_k.,_zijlstra,_j.g._&_links,_t.p._(2014)._radioiodine_therapy_for_hyperthyroidism._nederlands_tijdschrift_voor_geneeskunde,_158,_a6714._[online]_http",
"spil,_j.a.,_et_al._2013",
"spil,_j.a.,_muilekom,_h.a.m._&_van_de_walle-van_de_geijn,_b.f.h._(2013)._oncologie",
"stehouwer,_c.d.a._&_gans,_r.o.b._(1999)._klinisch_denken_en_beslissen_in_de_praktijk._een_patiënte_met_aanvallen_van_flushing._nederlands_tijdschrift_voor_geneeskunde,_143,_792-6._[online]_http",
"stehouwer,_c.d.a._&_gans,_r.o.b._1999",
"stone,_j.h.,_et_al._2012",
"stone,_j.h.,_zen,_y._&_deshpande,_v._(2012)._igg4-related_disease._the_new_england_journal_of_medicine,_366,_539-551._[online]_http",
"strianese,_d.,_et_al._2013",
"strianese,_d.,_piscopo,_r.,_elefante,_a.,_napoli,_m.,_comune,_c.,_baronissi,_i.,_et_al._(2013)._unilateral_proptosis_in_thyroid_eye_disease_with_subsequent_contralateral_involvement",
"studio-esthetique_2013",
"studio_esthetique._(2013)._micro_coagulatie_fibromen_|_steelwratjes._[online]_http",
"swedberg,_k.,_et_al._2013",
"swedberg,_k.,_young,_j.b.,_anand,_i.s.,_cheng,_s.,_desai,_a.s.,_diaz,_r.,_et_al._(2013)._treatment_of_anemia_with_darbepoetin_alfa_in_systolic_heart_failure._the_new_england_journal_of_medicine,_368,_1210-1219._[online]_http",
"syrimis,_a.",
"syrimis,_a._(s.d.)_finger_clubbing._[online]_http",
"systolic",
"systolisch",
"taalvinder._(2013)._[online]_http",
"taalvlinder",
"tachycardia",
"tachycardie",
"tachypnea",
"tachypneu",
"tachypnoea",
"te_velde,_l.f.,_blaauwwiekel,_e.e.,_sprenger,_h.g._&_weits,_j._(1997)._een_amoebenabces_in_de_lever;_vroeg_vermoeden,_late_detective._nederlands_tijdschrift_voor_geneeskunde,_141,_1436-9._[online]_http",
"te_velde,_l.f.,_et_al._1997",
"temmerman,_r._(2000)._towards_new_ways_of_terminology_description._the_sociocognitive_approach._amsterdam",
"temmerman,_r._2000",
"ten_houten,_r.,_et_al._2004",
"ten_houten,_r.,_meijer,_r.w._&_heitbrink,_m.a._(2004)._pijn_in_de_rug?_vergeet_de_buik_niet._nederlands_tijdschrift_voor_geneeskunde,_148,_1125-9._[online]_http",
"ter_avest,_p.c.,_et_al._2005",
"ter_avest,_p.c.,_tytgat,_g.a.m.,_westra,_m.,_peters,_m._&_van_den_berg,_j.m._(2005)._hemolytische_anemie_en_een_stollingsstoornis_als_eerste_manifestatie_van_cystische_fibrose_bij_twee_zuigelingen._nederlands_tijdschrift_voor_geneeskunde,149,_2125-8._[online]_http",
"the_new_england_journal_of_medicine",
"the_new_england_journal_of_medicine._(2014)._[online]_http",
"thomas,_k.s.,_crook,_a.m.,_nunn,_a.j.,_foster,_k.a.,_mason,_j.m.,_chalmers,_j.r.,_et_al._(2013)._penicillin_to_prevent_recurrent_leg_cellulitis._the_new_england_journal_of_medicine,_368,_1695-1703._[online]_http",
"thomas,_k.s.,_et_al._2013",
"thyroid",
"thyroid_gland",
"tita,_a.t.n.,_et_al._2009",
"tita,_a.t.n.,_landon,_m.b.,_y._spong,_c.y.,_lai,_y.,_leveno,_k.j.,_varner,_m.w.,_et_al._(2009)._timing_of_elective_repeat_cesarean_delivery_at_term_and_neonatal_outcomes._the_new_england_journal_of_medicine,_360,_111-120._[online]_http",
"tomlinson,_s.e.,_et_al._2010",
"tomlinson,_s.e.,_tan,_s.v.,_kullmann,_d.m.,_griggs,_r.c.,_burke,_d.,_hanna,_m.g.,_et_al._(2010)._nerve_excitability_studies_characterize_kv1.1_fast_potassium_channel_dysfunction_in_patients_with_episodic_ataxia_type._brain,_133(12),_3530–3540._[online]_http",
"torimitsu,_s.,_et_al._2012",
"torimitsu,_s.,_nemoto,_t.,_wakayama,_m.,_okubo,_y.,_yokose,_t.,_kitahara,_k.,_et_al._(2012)._literature_survey_on_epidemiology_and_pathology_of_cardiac_fibroma._european_journal_of_medical_research,_17(1),_5._[online]_http",
"trobe,_j._(2009)._proptosis._[online]_http",
"trobe,_j._2009",
"trommelstokvingers",
"tsea,_t._&_soergel,_d._(2003)._exploring_medical_expressions_used_by_consumers_and_the_media",
"tsea,_t._&_soergel,_d._2003",
"uitrekking",
"uitzetting",
"upperman,_j.s._&_barksdale,_e.m._(2004)._congenital_lymphedema._the_new_engand_journal_of_medicine,_350,_e5._[online]_http",
"upperman,_j.s._&_barksdale,_e.m._2004",
"urban_dictionary",
"urban_dictionary._(2006)._[online]_http",
"van_amsterdam,_j.g.c.,_et_al._2004",
"van_amsterdam,_j.g.c.,_opperhuizen,_a.,_van_den_brink,_w._(2004)._cannabis_als_risicofactor_van_schizofrenie._tijdschrift_voor_psychiatrie,_46(8),_515–524._[online]_http",
"van_bon-martens,_m.j.h.,_et_al._2001",
"van_bon-martens,_m.j.h.,_klingenberg,_h.,_dijkstra,_h.a.j._&_peeters,_p.h.m._(2001)._borstklachten_ten_tijde_van_bevolkingsonderzoek_naar_borstkanker",
"van_bost,_g.,_et_al._2005",
"van_bost,_g.,_lorent,_g._&_crombez,g._(2005)._aanvaarding_na_niet-aangeboren_hersenletsel._gedragstherapie,_38(4),_247._[online]_http",
"van_dale_3d,_online",
"van_dale_3d_online._(2013)._[online]_http",
"van_dale_en,_online",
"van_dale_en._(2013)._[online]_http",
"van_dale_ne,_online",
"van_dale_ne._(2013)._[online]_http",
"van_dale_nn,_online",
"van_dale_nn._(2013)._[online]_http",
"van_de_ploeg,_a.t.,_et_al._2010",
"van_de_warrenburg,_b.p.c._(2001)._autosomaal_dominante_cerebellaire_ataxieën_in_nederland",
"van_de_warrenburg,_b.p.c._2001",
"van_den_berkmortel,_f.w.p.j.,_et_al._1995",
"van_den_berkmortel,_f.w.p.j.,_wollersheim,_h.,_heijstraten,_f.m.j._&_thien,_th._(1995)._vijf_patiënten_met_de_ziekte_van_takayasu_in_nederland._nederlands_tijdschrift_voor_geneeskunde,_139,_1127-32._[online]_http",
"van_den_tol,_d.c.,_et_al._1998",
"van_den_tol,_d.c.,_van_der_werf,_t.s.,_hamer,_j.p.m.,_tulleken,_j.e.,_ligtenberg,_j.j.m._&_zijlstra,_j.g._(1998)._respiratoir_falen_soms_toch_door_cardiale_oorzaak._nederlands_tijdschrift_voor_geneeskunde,_142,_1937-41._[online]_http",
"van_der_eerden,_m.m.,_de_graaff,_c.s.,_boersma,_w.g._&_vlaspolder,_f._(2006)._faryngitis_met_een_holtevormende_pneumonie_veroorzaakt_door_arcanobacterium_haemolyticum._nederlands_tijdschrift_voor_geneeskunde,_150,_1139-42._[online]_http",
"van_der_eerden,_m.m.,_et_al._2006",
"van_der_graaff,_m._(2011)._cfh-rapport_11/29_aztreonam._diemen",
"van_der_graaff,_m._2011",
"van_der_maas,_p.j._(2000)._bevolkingsonderzoek_naar_borstkanker",
"van_der_maas,_p.j._2000",
"van_der_ploeg,_a.t.,_clemens,_p.r.,_corzo,_d.,_escolar,_d.m.,_florence,_j.,_groeneveld,_g.j.,_et_al._(2010)._a_randomized_study_of_alglucosidase_alfa_in_late-onset_pompe’s_disease._the_new_england_journal_of_medicine,_362,_1396-406._[online]_http",
"van_der_vliet,_h.j.j._&_van_bodegraven,_a.a._(2004)._megacolon_tijdens_lactulosetherapie._nederlands_tijdschrift_voor_geneeskunde,_148,_998-1001._[online]_http",
"van_der_vliet,_h.j.j._&_van_bodegraven,_a.a._2004",
"van_dongen,_c._(2012)._dexamethasonspuit_helpt_maar_kort_bij_hielspoor._nederlands_tijdschrift_voor_geneeskunde,156,_c1355._[online]_http",
"van_dongen,_c._2012",
"van_donselaar-van_der_pant,_k.a.m.i.,_buwalda,_m._&_van_leeuwen,_h.j._(2008)._lidocaïne",
"van_donselaar-van_der_pant,_k.a.m.i.,_et_al._2008",
"van_ginkel,_r.,_büller,_h.a.,_heymans,_h.s.a.,_taminiau,_j.a.j.m.,_boeckxstaens_&_benninga,_m.a._(2003)._functionele_gastro-intestinale_ziektebeelden_op_de_kinderleeftijd._ii._obstipatie_en_solitaire_encopresis;_fysiologie_en_pathofysiologie._nederlands_tijdschrift_voor_geneeskunde,_147,_1264-7._[online]_http",
"van_ginkel,_r.,_et_al._2003",
"van_herendael,_h.e.,_et_al._2006",
"van_herendael,_h.e.,_van_den_heuvel,_m.c.,_van_roey,_g.w._&_soetens,_f.m._(2006)._re-expansielongoedeem_bij_een_patiënt_na_behandeling_van_een_pneumothorax._nederlands_tijdschrift_voor_geneeskunde,_150,_259-62._[online]_http",
"van_klaveren,_r.j.,_et_al._2009",
"van_laake,_l.w.,_broeders,_j.a.j.l.,_baur,_l.h.b._&_salomonsz,_r._(2006)._stressechocardiografie_bij_11_patiënten_met_ischemische_klachten_en_een_myocardbrug",
"van_laake,_l.w.,_et_al._2006",
"van_maanen,_h._(2013)._is_een_beetje_angst_goed_voor_de_copd-patiënt?._nederlands_tijdschrift_voor_geneeskunde,_157,_c1623._[online]_http",
"van_maanen,_h._2013",
"van_montfrans,_c.,_de_boer,_e.m.,_jansma,_e.p.,_gibbs,_s.,_mekkes,_j.r.,_van_der_vleuten,_c.j.m.,_et_al._behandeling_van_patiënten_met_een_veneus_ulcus_cruris._nederlands_tijdschrift_voor_geneeskunde,_157,_a5647._[online]_http",
"van_montfrans,_c.,_et_al._2013",
"van_osselen,_c._(2011)._seroom_na_borstkankeroperatie_spreekt_niet_vanzelf._nederlands_tijdschrift_voor_geneeskunde,_155,_c1066._[online]_http",
"van_osselen,_c._2011",
"van_ravenswaaij-arts,_c.m.a.,_et_al._2002",
"van_ravenswaaij-arts,_c.m.a.,_van_den_ouweland,_a.m.w.,_hoogeboom,_a.j.m.,_herbergs,_j._&_pals,_g._(2002)._van_gen_naar_ziekte;_craniosynostosesyndromen_door_fgfr2-mutaties._nederlands_tijdschrift_voor_geneeskunde,_146,_63-6._[online]_http",
"van_stralen-bohlmann,_a._&_streefkerk,_j.g._(1995)._kleine_kwalen_in_de_huisartsgeneeskunde;_chloasma_of_zwangerschapsmasker._nederlands_tijdschrift_voor_geneeskunde,_139,_1971-5._[online]_http",
"van_stralen-bohlmann,_a._&_streefkerk,_j.g._1995",
"van_urk,_p.r.,_et_al._2014",
"van_urk,_p.r.,_van_den_berg,_m.p.,_van_royen,_b.j.,_smeets,_e.e.j._&_curfs,_l.m.g._(2014)._het_rett-syndroom._nederlands_tijdschrift_voor_geneeskunde,_158,_a6686._[online]_http",
"van_vanrooij,_t._(2012)._roken_en_hypertensie_verhogen_risico_sab_ook_bij_aanleg_hiervoor._nederlands_tijdschrift_voor_geneeskunde,_156,_c1292._[online]_http",
"van_vanrooij,_t._2012",
"van_velthoven,_m.e.j.,_et_al._2003",
"van_velthoven,_m.e.j.,_wittebol-post,_d.,_berendschot,_t.t.j.m._&_mourits,_m.p._(2003)._traanwegsondage_bij_jonge_kinderen_met_een_aangeboren_traanwegobstructie_in_het_universitair_medisch_centrum_utrecht",
"van_venrooij,_t._(2012)._prikkelbaredarmsyndroom_mogelijk_niet_geassocieerd_met_ontsteking._nederlands_tijdschrift_voor_geneeskunde,_156,_c1328._[online]_http",
"van_venrooij,_t._2012",
"van_weelden,_k._(2012)._thuis_sterven_in_belgië_verdient_aandacht._nederlands_tijdschrift_voor_geneeskunde,_156,_c1230._[online]_http",
"van_weelden,_k._2012",
"van_wolferen,_s.a.,_et_al._2005",
"van_wolferen,_s.a.,_vonk_noordegraaf,_a.,_boonstra,_a._&_postmus,_p.e._(2005)._pulmonale_arteriële_hypertensie_door_amfetaminen_gebruikt_als_drugs_of_doping._nederlands_tijdschrift_voor_geneeskunde,_149,_1283-8._[online]_http",
"van_wouwe,_j.p.,_et_al._2004",
"van_wouwe,_j.p.,_mattiazzo,_g.f.,_el_mokadem,_n.,_reeser,_h.m._&_hirasing,_r.a._(2004)._de_incidentie_en_de_eerste_symptomen_van_diabetes_mellitus_type_1_bij_0-14-jarigen_in_nederland,_1996-1999._nederlands_tijdschrift_voor_geneeskunde,_148,_1824-9._[online]_http",
"vegelin,_a.l.,_et_al._1998",
"vegelin,_a.l.,_van_vught,_a.j.,_wolfs,_t.f.w.,_kimpen,_j.l.l._&_geelen,_s.p.m._(1998)._kinkhoest_bij_de_jonge_zuigeling._nederlands_tijdschrift_voor_geneeskunde,_142,_2657-60._[online]_http",
"veling,_w.,_blom,_m.b.j._&_hoek,_h.w._(2013)._depressie_bij_allochtonen_in_de_spreekkamer._nederlands_tijdschrift_voor_geneeskunde,_157,_a5606._[online]_http",
"veling,_w.,_et_al._2013",
"vergeldt,_t.f.m.,_et_al._2014",
"vergeldt,_t.f.m.,_kortenhorst,_m.s.q.,_hasaart,_t.h.m._&_wijnberger,_l.d.e._(2014)._shock_in_de_zwangerschap._nederlands_tijdschrift_voor_geneeskunde,_158,_a6606._[online]_http",
"verhoef,_s.,_et_al._2001",
"verhoef,_s.,_lindhout,_d.,_hallay,_d.j.j._&_van_den_ouweland,_a.m.w._(2001)._van_gen_naar_ziekte;_de_tsc1-_en_tsc2-genen_en_tubereuze-sclerosiscomplex._nederlands_tijdschrift_voor_geneeskunde,_145,_1928-30._[online]_http",
"vermeulen,_m.r._(2013)._nekpijn",
"vermeulen,_m.r._2013",
"verrijn_stuart,_a.a.,_de_vroede,_m.a.m.j._&_giltay,_j.c._(2005)._van_gen_naar_ziekte;_congenitale_bijnierschorshypoplasie_en_het_dax-1-gen._nederlands_tijdschrift_voor_geneeskunde,_149,_1156-8._[online]_http",
"verrijn_stuart,_a.a.,_et_al._2005",
"versnelde_ademhaling",
"verwijding_van_slagader",
"vierhout,_m._e._&_lammes,_f._b._(2008)._praktische_gynaecologie._houten",
"vierhout,_m._e._&_lammes,_f._b._2008",
"vinjé-harrewijn,_a.,_van_beek,_a._&_haspels,_p._(2012)._omgaan_met_lymfoedeem._houten",
"vinjé-harrewijn,_a._et_al._2012",
"violari,_a.,_cotton,_m.f.,_gibb,_d.m.,_babiker,_a.g.,_steyn,_j.,_madhi,_s.a.,_et_al._(2008)._early_antiretroviral_therapy_and_mortality_among_hiv-infected_infants._the_new_england_journal_of_medicine,_359,_2233-44._[online]_http",
"violari,_a.,_et_al._2008",
"violaris,_k.,_bitzos,_e._&_rudolph,_n._(1986)._increased_blood_viscosity_and_tachypnoea_in_infants_of_diabetic_mothers._archives_of_disease_in_childhood,_61(9),_910–912._[online]_http",
"violaris,_k.,_et_al._1986",
"vleesboom",
"vlekkerig",
"vlekkig",
"vochtophoping",
"vogtländer,_n.p.j.,_et_al._2004",
"vogtländer,_n.p.j.,_rietjens,_s.j.,_van_der_vlag,_j._&_berden,_j.h.m._(2004)._podocytdisfunctie_en_proteïnurie._nederlands_tijdschrift_voor_geneeskunde,_148,712-8._[online]_http",
"voor_radiologie,_n.v._&_voor_heelkunde,_n.v._(2005)._diagnostiek_en_behandeling_van_arterieel_vaatlijden_van_de_onderste_extremiteit._(van_zuiden_communications_b.v)._[online]_http",
"voor_radiologie,_n.v._&_voor_heelkunde,_n.v._2005",
"vos,_m.s._&_berendsen,_h.h._(2001)._dokter,_ik_wil_het_niet_weten_-_verkenning_van_ontkenning_bij_patiënten_met_longkanker._nederlands_tijdschrift_voor_geneeskunde,_145,_2409-12._[online]_http",
"vos,_m.s._&_berendsen,_h.h._2001",
"vos,_p.a.j.m.,_bijlsma,_j.w.j._&_derksen,_r.h.w.m._(2005)._polymyalgia_rheumatica_en_arteriitis_temporalis._nederlands_tijdschrift_voor_geneeskunde,_149,_1932-7._[online]_http",
"vos,_p.a.j.m.,_et_al._2005",
"vriens,_m.r.,_et_al._2013",
"vriens,_m.r.,_kist,_j.w.,_lodewijk,_l.,_van_hillegersberg,_r._&_borel_rinkes,_i.h.m._(2013)._robotgeassisteerde_transaxillaire_schildklieroperatie._nederlands_tijdschrift_voor_geneeskunde,_157,_a5841._[online]_http",
"wadensjö,_c.,_dimitrova,_b.e._&_nilsson,_a._(2007)._the_critical_link_4._amsterdam",
"wadensjö,_c.,_et_al._2007",
"wang,_j.b.s.,_cortina,_g.,_wu,_s.v.,_tran,_r.,_cho,_j._&_tsai,m._(2006)._mutant_neurogenin-3_in_congenital_malabsorptive_diarrhea._the_new_england_journal_for_medicine,_355,_270-280._[online]_http",
"wang,_j.b.s.,_et_al._2006",
"wang,_t.j.,_et_al._2004",
"wang,_t.j.,_larson,_m.g.,_levy,_d.,_benjamin,_e.j.,_leip,_e.p.,_omland,_t.,_et_al._(2004)._plasma_natriuretic_peptide_levels_and_the_risk_of_cardiovascular_events_and_death._the_new_england_journal_of_medicine,_350,_655-63._[online]_http",
"weber,_w.e.j._(2002)._cerebrale_blindheid._nederlands_tijdschrift_voor_geneeskunde,_146,_2013-6._[onine]_http",
"weber,_w.e.j._2002",
"weinstein,_s.l.,_dolan,_l.a.,_wright,_j.g._&_dobbs,_m.b._(2013)._effects_of_bracing_in_adolescents_with_idiopathic_scoliosis._the_new_england_journal_of_medicine,_369,_1512-1521._[online]_http",
"weinstein,_s.l.,_et_al._2013",
"wells,_j.m.,_et_al._2012",
"wells,_j.m.,_washko,_g.r.,_han,_m.k.,_abbas,_n.,_nath,_h.,_mamary,_j.,_et_al._(2012)._pulmonary_arterial_enlargement_and_acute_exacerbations_of_copd._the_new_england_journal_of_medicine,_367,_913-921._[online]_http",
"wenzel,_r.p._&_fowler,_a.a._(2006)._acute_bronchitis._the_new_england_journal_of_medicine,_355,_2125-2130._[online]_http",
"wenzel,_r.p._&_fowler,_a.a._2006",
"whyte,_m.,_et_al.2012",
"whyte,_m.,_greenberg,_c.r.,_salman,_n.j.,_bober,_m.b,_mcalister,_w.h.,_wenkert,_d.,_et_al._(2012)._enzyme-replacement_therapy_in_life-threatening_hypophosphatasia._the_new_england_journal_of_medicine,_366,_904-13._[online]_http",
"wiemer,_n.g.m.,_et_al._2006",
"wiemer,_n.g.m.,_polak,_b.c.p._&_veckeneer,_m.a.h._(2006)._behandelingsmogelijkheden_voor_diabetisch_macula-oedeem._nederlands_tijdschrift_voor_geneeskunde,_150,_2183-7_[online]_http",
"wiersinga,_w.j._&_van_der_poll,_t._(2010)._sepsis",
"wiersinga,_w.j._&_van_der_poll,_t._2010",
"wijsbek,_h._(2013)._euthanasie_bij_gevorderde_dementie",
"wijsbek,_h._2013",
"willemsen,_w.n.p.,_de_kruif,_j.h.,_velthausz,_m.b.f._&_meelen,_b.t.h.m._(2000)._myomen_en_vruchtbaarheid._nederlands_tijdschrift_voor_geneeskunde,_144,_789-91._[online]_http",
"willemsen,_w.n.p.,_et_al_2000",
"william,_j.m.g.,_barnhofer,_t.,_crane,_c.,_duggan,_d.s.,_shah,_d.,_brennan,_k.,_et_al._(2012)._pre-adult_onset_and_patterns_of_suicidality_in_patients_with_a_history_of_recurrent_depression._journal_of_affective_disorders;_138(1-2),_173-179._[online]_http",
"william,_j.m.g.,_et_al._2012",
"williams,_n._&_ogden,_j._(2004)._the_impact_of_matching_the_patients_vocabulary",
"williams,_n._&_ogden,_j._2004",
"willmott,_f.e._(1988)._mucopurulent_cervicitis",
"willmott,_f.e._1988",
"winterberg,_d.h._(2005)._diagnose_in_beeld_(233)._een_meisje_met_gegroefde_nagels._nederlands_tijdschrift_voor_geneeskunde,_149,_702._[online]_http",
"winterberg,_d.h._2005",
"witsenburg,_m.,_et_al._2004",
"witsenburg,_m.,_van_osch-gevers,_m.,_&_strengers,_j._(2004). cardiologie,_vol._6._houten",
"woorden-boek.nl",
"woorden-boek.nl._(s.d.)._[online]_http",
"woordenboek_nederlands",
"woordenboek_nederlands._(2014)._[online]_http",
"wright,_s.e._&_budin,_g._(1997)._handbook_of_terminology_management",
"wright,_s.e._&_budin,_g._1997",
"zaaijer,_h.l.,_et_al._1999",
"zaaijer,_h.l.,_savelkoul,_p.h.m._&_vandenbroucke-grauls,_c.m.j.e._(1999). de_ziekte_van_whipple._nederlands_tijdschrift_voor_geneeskunde,_143,_388-92._[online]_http",
"zhuang,_z.,_et_al._2012",
"zhuang,_z.,_yang,_c.,_lorenzo,_f.,_merino,_m.,_fojo,_t.,_kebebew,_e.,_et_al._(2012)._somatic_hif2a_gain-of-function_mutations_in_paraganglioma_with_polycythemia._the_new_england_journal_of_medicine,_367,_922-930._[online]_http",
"zielstorff,_r.d._(2003)._controlled_vocabularies_for_consumer_health._journal_of_biomedical_informatics,_36(4-5),_326–333._[online]_http",
"zielstorff,_r.d._2003",
"zubillaga,_a._f.,_et_al._1994",
"zubillaga,_a._f.,_guglielmi,_g.,_vi,_f._&_duckwiler,_g._r._(1994)._endovascular_occlusion_of_intracranial_aneurysms_with_electrically_detachable_coils",
"zur,_b.,_et_al._2012",
"zur,_b.,_mayer-hubner,_b.,_ludwig,_m._&_stoffel-wagner,_b._(2012)._a_14-year-old_boy_with_chronic_cyanosis,_mild_anemia,_and_limited_physical_resistance_to_stress._clinical_chemistry,_58(2),_332._[online]_http",
"zweetafscheiding",
"zwelling",
"z"];
window.termUrls = new Map();
termUrls.set("c", "browser_en_C_D_1.html");
termUrls.set("e", "browser_en_E_F_1.html");
termUrls.set("g", "browser_en_G_H_1.html");


let arr = Array.from(termUrls.keys());
window.valueOfTextField = "";
window.text = "";
document.getElementById("myInput").style.borderColor = "blue";
 
autocomplete(document.getElementById("myInput"), arr);


function autocomplete(inp, arr) {
    /*the autocomplete function takes two arguments,
     the text field element and an array of possible autocompleted values:*/
    var currentFocus;
    /*execute a function when someone writes in the text field:*/
    inp.addEventListener("input", function (e) {
        var a, b, i, val = this.value;
        /*close any already open lists of autocompleted values*/
        closeAllLists();
        if (!val) {
            return false;
        }
        currentFocus = -1;
        /*create a DIV element that will contain the items (values):*/
        a = document.createElement("DIV");
        a.setAttribute("id", this.id + "autocomplete-list");
        a.setAttribute("class", "autocomplete-items");
        /*append the DIV element as a child of the autocomplete container:*/
        this.parentNode.appendChild(a);
        /*for each item in the array...*/
        for (i = 0; i < arr.length; i++) {
            window.text = arr[i];
            /*check if the item starts with the same letters as the text field value:*/
            if (arr[i].substr(0, val.length).toUpperCase() == val.toUpperCase()) {
                /*create a DIV element for each matching element:*/
                b = document.createElement("DIV");
                /*make the matching letters bold:*/
                b.innerHTML = "<strong>" + arr[i].substr(0, val.length) + "</strong>";
                b.innerHTML += arr[i].substr(val.length);
                /*insert a input field that will hold the current array item's value:*/
                b.innerHTML += "<input type='hidden' value='" + arr[i] + "'>";
                /*execute a function when someone clicks on the item value (DIV element):*/
                b.addEventListener("click", function (e) {
                    /*insert the value for the autocomplete text field:*/
                    inp.value = this.getElementsByTagName("input")[0].value;
                    window.text = this.getElementsByTagName("input")[0].value;

                    /*close the list of autocompleted values,
                     (or any other open lists of autocompleted values:*/
                    closeAllLists();
                });
                a.appendChild(b);
            }
        }
    });
    /*execute a function presses a key on the keyboard:*/
    inp.addEventListener("keydown", function (e) {
        var x = document.getElementById(this.id + "autocomplete-list");
        if (x)
            x = x.getElementsByTagName("div");
        if (e.keyCode == 40) {
            /*If the arrow DOWN key is pressed,
             increase the currentFocus variable:*/
            currentFocus++;
            /*and and make the current item more visible:*/
            addActive(x);
        } else if (e.keyCode == 38) { //up
            /*If the arrow UP key is pressed,
             decrease the currentFocus variable:*/
            currentFocus--;
            /*and and make the current item more visible:*/
            addActive(x);
        } else if (e.keyCode == 13) {
            /*If the ENTER key is pressed, prevent the form from being submitted,*/
            e.preventDefault();
            if (currentFocus > -1) {
                /*and simulate a click on the "active" item:*/
                if (x)
                    x[currentFocus].click();
            }
        }
    });
    function addActive(x) {
        /*a function to classify an item as "active":*/
        if (!x)
            return false;
        /*start by removing the "active" class on all items:*/
        removeActive(x);
        if (currentFocus >= x.length)
            currentFocus = 0;
        if (currentFocus < 0)
            currentFocus = (x.length - 1);
        /*add class "autocomplete-active":*/
        x[currentFocus].classList.add("autocomplete-active");
    }
    function removeActive(x) {
        /*a function to remove the "active" class from all autocomplete items:*/
        for (var i = 0; i < x.length; i++) {
            x[i].classList.remove("autocomplete-active");
        }
    }
    function closeAllLists(elmnt) {
        /*close all autocomplete lists in the document,
         except the one passed as an argument:*/
        var x = document.getElementsByClassName("autocomplete-items");
        for (var i = 0; i < x.length; i++) {
            if (elmnt != x[i] && elmnt != inp) {
                x[i].parentNode.removeChild(x[i]);
            }
        }
    }
    document.addEventListener("click", function (e) {
        //document.getElementById("myInput").value=window.valueOfTextField;
        //document.getElementById('form_id').action = window.location.href = window.valueOfTextField; //Will set it
        closeAllLists(e.target);
    });

    document.getElementById("form_id").addEventListener("submit", myFunction);
    function myFunction() {
        window.valueOfTextField = window.termUrls.get(window.text);
        if(document.getElementById("myInput").value == ""){
           alert("search box is empty")
          }
        else{
        document.getElementById('form_id').action = window.location.href = window.valueOfTextField; //Will set it
        }
     }
    
    
}
